### ISSUE TITLE
[Menu] Is there any ways to disable the focus on mount?

### ISSUE THREAD

**Issue by mehranhatami** [mlaursen/react-md#1059]
Maybe this can be considered a feature request but I am not entirely sure. I am using the `DropdownMenu` component and when mounting the `Menu` the first item in the menu is always automatically focused. I quickly looked into the code and I noticed that `Menu` is using a hook called `useFocusOnMount` and its fifth argument is always `undefined`. Is there any other way to disable the focusOnMount so that when the menu is mounted the focus stays on the MenuButton and the user can only navigate through the menu items using the up and down arrow keys?

**Comment by mlaursen** [comment]
Would you mind providing the use case for why the button needs to be the focus instead of the menu/menuitem? The current behavior _should_ be:
- click/focus menu button
- menu gains focus
- first/last/specific menu item gains focus
- keyboard interaction to move within menu
- user closes menu by one of:
  - escape key
  - tab or shift + tab
  - click a menu item with space or enter
  - click a menu item with the mouse
  - click outside of the menu
- once the menu is closed, the menu button or last focused DOM element should regain focus (except for click outside of the menu and shift/shift + tab)

Is there an issue of losing focus in your use case or some other error?

I might be able to look into updating the `Menu` to support `aria-activedescendant` (visual focus only like the `Listbox`/`Autocomplete`) movement, but that might take a bit.

**Comment by mehranhatami** [comment]
@mlaursen Thank you for the reply. For the DropdownMenu component, it works exactly as you have mentioned in the message as long as you implement it with the default menu renderer. In my case, though I need to make sure the `Menu` rendered by the Dropdown has `unmountOnExit` as `false` and that's why I have a custom `menuRenderer` like this:

```javascript
export const menuRenderer = ({
  horizontal,
  children,
  classNames,
  ...props
}) => (
  <Menu
    {...props}
    horizontal={horizontal}
    unmountOnExit={false}
    classNames={scaleClassNames} 
  >
    <List horizontal={horizontal}>{children}</List>
  </Menu>
);
```

But when using this `menuRenderer` only the first time that the `DropdownMenu` is opened the focus follows the mentioned flow. For the second time, the default focus is not working as expected since the focus logic is only handled when the menu is mounted.

Regarding my specific use-case and why I need it, I can say that sometimes the `MenuItem` I have in my `Menu` is supposed to open modals that are contained (rendered as a react portal) in their `MenuItem` component and if the Menu gets unmounted when clicking on that MenuItem then the Modal will also be unmounted. I could of course use only the `Menu` component and create my own `DropdownMenu` component that handles the `unmountOnExit` but I thought it might make more sense to consider creating a PR and contributing to this library instead but I was not sure if it is aligned with what you are doing and planning for this library.

**Comment by mlaursen** [comment]
Great, thank you! That helps explain this request a lot more. I haven't actually tested the `unmountOnExit` being `false` for the `Menu` so this is good info and a reasonable request.

**Comment by mehranhatami** [comment]
@mlaursen FYI for the `DropdownMenu` to support `unmountOnExit` being `false`. I had to also pass a customized list of transition `classNames` like this:
```javascript
import { SCALE_CLASSNAMES } from '@react-md/transition/lib/constants';

export const scaleClassNames = {
  ...SCALE_CLASSNAMES,
  exitDone: style.MenuHidden,
};
```
and I have this for the `.MenuHidden` css:
```css
.MenuHidden {
  display: none;
}
```
So that when the transition exits the menu gets hidden.

I thought this might be helpful if you want to take a look into it.
