### ISSUE TITLE
Allow Toggleable Layout to be visible by default

### ISSUE THREAD

**Issue by its-ratikant** [mlaursen/react-md#1066]
Hi,

Can you please give me some hints on how to show or hide toggleable layout nav programmatically or by default open mode?

Thanks!!

**Comment by mlaursen** [comment]
Whoops... I think I'll need to add some more props to the layout to make this easier to work with in the future as well as some more `Layout` examples. However, you can implement this _somewhat_ for now by using the [`useLayoutConfig` hook](https://github.com/mlaursen/react-md/blob/9acbefa1c6f430fcdae917aaf1a84ac267345f41/packages/layout/src/LayoutProvider.tsx#L35-L77) in a child component of the `Layout`.


The only downside to this approach is that if the user resizes from a non-toggleable layout to the toggleable layout, it will still animate in since the it is [temporarily set to hidden](https://github.com/mlaursen/react-md/blob/9acbefa1c6f430fcdae917aaf1a84ac267345f41/packages/layout/src/LayoutProvider.tsx#L122-L129).

Here's a quick [codesandbox](https://codesandbox.io/s/react-md-updated-toggleable-layout-to-start-visible-q29go?file=/src/App.tsx:425-909) for it and below is the code that handles the visibility:


```tsx
const { showNav, visible, layout } = useLayoutConfig();

const firstRender = useRef(true);
const prevLayout = useRef(layout);
if (firstRender.current || layout !== prevLayout.current) {
  // if it's the first render OR the layout has changed, need to see if the
  // current layout is toggleable and make sure that it is visible
  prevLayout.current = layout;
  firstRender.current = false;
  if (!visible && isToggleableLayout(layout)) {
    showNav();
  }
}
```

**Comment by mlaursen** [comment]
I think I'll add a new prop: `defaultToggleableVisible` to help with this. If it is set to `true`, the toggleable layout will start as visible instead of hidden.

**Comment by its-ratikant** [comment]
Perfect! Thanks a lot!
