### ISSUE TITLE
What is the recommanded way to create a form?

### ISSUE THREAD

**Issue by gutenye** [mlaursen/react-md#115]
I'm new to react, struggling to find a easy way to create a from. And Material Design does not have a spec for form.

Instead of using `onChange` on every `<input>`, maybe we can do something like

```
<form onSubmit={onSubmit}>
  <TextField name="email" />
  <RaisedButton type="submit" label="Submit" />
</form>
```

At the moment TextField does not support name props.

**Comment by mlaursen** [comment]
Handling forms is usually a pain because of all the validation that needs to happen for them. You could try using [formsy-react](/christianalfoni/formsy-react) to handle that for you.

It is best from a user's experience to not have errors appear only when they submit, so it is best to have validation occurring on blur or change. You can attach it to each input, or on the global `<form>`. But you are right, text field's do not currently support the `name` prop (accidental removal), so the global one would be hard. I'll fix that for the `0.3.3` release.

The only things I have found with forms in material design is the [Errors -Pattern](https://material.google.com/patterns/errors.html#errors-user-input-errors). Not sure if that will help you  much though.

**Comment by grimunit** [comment]
I've been using both formsy-react and formsy-material-ui for forms and it seems to be working pretty good so far. Tons of hooks into all the different validation use cases with really good documentation.

**Comment by gutenye** [comment]
Thanks, I'll look into them.
