### ISSUE TITLE
Change navigation type from mini to regular (or opposite) on resize causes rerender when the appbar is not fixed

### ISSUE THREAD

**Issue by Nureckiy** [mlaursen/react-md#1207]
When mini and non-mini layout types are used for different screen sizes and the position of the app bar is not fixed, screen resizing that causes the layout type to change will also unnecessarily re-render the component.

**To Reproduce** Steps to reproduce the behavior:

1. Set different types of layouts (in my example, `temporary-mini` and `full-height`)
2. Set `fixed: false` for `appBarProps`;
3. Try resizing the screen to change the layout type
4. See how the component is redrawn

Here is a sandbox describing the behavior (try clicking the "Click me" button to change the state of the component, then resize, the state will be reset): https://codesandbox.io/s/nervous-snowflake-spcbl

**Screenshots**
Before resize (test value is "TRUE"):
![image](https://user-images.githubusercontent.com/17616120/126899823-0863acdb-0e5f-4dfd-8486-6e383925f274.png)

After resizing (state reset):
![image](https://user-images.githubusercontent.com/17616120/126899845-3ab5e0a3-5176-4b18-acc6-6799bbb9bc96.png)

**Package version is 2.9.0**

Thanks!

**Comment by mlaursen** [comment]
This bug is caused by switching from [rendering the content as a fragment](https://github.com/mlaursen/react-md/blob/58f614b38b5a7dcca6a84319275320b9863cba87/packages/layout/src/MiniLayoutWrapper.tsx#L94-L101) to [rendering in a div for grid styles](https://github.com/mlaursen/react-md/blob/58f614b38b5a7dcca6a84319275320b9863cba87/packages/layout/src/MiniLayoutWrapper.tsx#L136-L144) which causes the `children` to re-mount (losing state). I'll go with updating the `MiniLayoutWrapper` to always render the `<div>` if any of the layout types are `mini` which will prevent the children from re-mounting to fix this issue.

This has a small side effect of always rendering a `<div>` around the `<main>` content which _might_ cause a CSS issue for the non-mini layouts in your app. If you do run into a CSS issue, additional props/styles can be provided to this wrapper `<div>` with the [miniWrapperProps](https://github.com/mlaursen/react-md/blob/58f614b38b5a7dcca6a84319275320b9863cba87/packages/layout/src/LayoutChildren.tsx#L70-L85).
