### ISSUE TITLE
FileInput default icon is `download`, should be `file_upload`

### ISSUE THREAD

**Issue by stickfigure** [mlaursen/react-md#1325]
FileInput.tsx line 100, looks like the wrong icon. Should be an upload icon, not a download icon.

react-md 4.0.2

**Comment by mlaursen** [comment]
Whoops -- I'll update the default [`download` icon](https://github.com/mlaursen/react-md/blob/3521e9b4feed1e9dbfa50fa8fd4562bc642993b4/packages/icon/src/IconProvider.tsx#L92) to be `file_upload` instead of `file_download`.

In the next major release, I'll rename the `download` icon to be `upload` so the naming matches better. The renaming is really only a breaking change if users of this library override these icons like my [documentation website](https://github.com/mlaursen/react-md/blob/3521e9b4feed1e9dbfa50fa8fd4562bc642993b4/packages/documentation/src/components/Layout/Layout.tsx#L49-L63) or the [examples in this repo](https://github.com/mlaursen/react-md/blob/3521e9b4feed1e9dbfa50fa8fd4562bc642993b4/examples/create-react-app/src/components/Layout/Layout.js#L23-L37).
