### ISSUE TITLE
[Question] Can I change mouse hover timeout before tooltip appears?

### ISSUE THREAD

**Issue by tuhlmann** [mlaursen/react-md#1367]
Hi,

this is a React-MD 5 question, and I apologized if that's the wrong channel for questions.

I'm using `<Tooltipped />` to create a tooltip around my component. 

I would like to change the default time the mouse has to hover over the dom element until the tooltip appears, but I couldn't find any prop that would allow me to do that.

Is that possible with the current release?

Thanks!

**Comment by mlaursen** [comment]
Yeap! This should be possible by wrapping your `<Tooltipped />` component or part of your React tree with `<HoverModeProvider defaultVisibileInTIme={TIME_IN_MS}>`. I think I updated the tooltip components to use the "hover mode" functionality around 2.8.0 but I haven't found a good way to reflect these changes in the documentation.

- [HoverModeProvider props/options](https://github.com/mlaursen/react-md/blob/2cba44aafea3fc06d2ecfa69ea7c33b035395dfe/packages/utils/src/hover/HoverModeProvider.tsx#L38-L77)
- [useTooltip focus/touch delay options](https://github.com/mlaursen/react-md/blob/2cba44aafea3fc06d2ecfa69ea7c33b035395dfe/packages/tooltip/src/useTooltip.ts#L184-L199) -- I'm not 100% sure if these are available in the `Tooltipped` component though since I kind of deprecated the `Tooltipped` component in favor of this hook.

**Comment by tuhlmann** [comment]
Awesome, thank you for your quick reply!
I might then change the code to use the hook instead of the component if that's the preferred future proof way.

Thanks!
