### ISSUE TITLE
Dirty look and feel of form inputs

### ISSUE THREAD

**Issue by albenik** [mlaursen/react-md#143]
Components on screenshot:
- Checkbox
- TextField
- Select
1. By default  vertical arranged form inputs have different right margins
2. Inconsistent font sizes of form inputs

![screen shot 2016-10-06 at 17 09 26](https://cloud.githubusercontent.com/assets/1047425/19155652/e49a4c24-8be7-11e6-8530-71b9b2a9cf7c.png)

**Comment by mlaursen** [comment]
This should be fixed once I finish up my refactoring branch. I've made the form controls behave a bit more like bootstrap out of the box -- full width text fields by default and removed the weird padding on text fields. I also implemented the material design grid system, so that should help as well.

I hadn't thought about the label size for the selection controls since the design docs only specified different label sizes for text fields. I'll make sure to update that

Would you mind explaining more about the right margins?

**Comment by albenik** [comment]
@mlaursen Sorry, my mistake: **LEFT** margins wrong, not right.
![screen shot 2016-10-06 at 17 09 26](https://cloud.githubusercontent.com/assets/1047425/19185764/b7622c5a-8c8b-11e6-9bbc-31f8be712d0c.png)

**Comment by mlaursen** [comment]
Ok, so I have gotten farther and nearing the end of the `v1.0.0` release. Currently a form with both selection controls and text/select fields looks like this:

![screen shot 2016-11-06 at 8 58 08 am](https://cloud.githubusercontent.com/assets/3920850/20039343/4b8bbb0a-a3ff-11e6-8ff4-cbc10dafa409.png)

If you want to have the text fields and other content aligned with a selection control, you just need to add `padding-left: 12px` to those elements.

I could either supply the styles:

```scss
.md-selection-control-container ~ *:not(.md-selection-control-container) {
  padding-left: 12px;
}
```

or

```scss
.md-selelection-control-relative {
  padding-left: 12px;
}
```

The first one would work pretty well if your grid is set up nicely, but might cause too many problems. The second one would be a lot safer, but you would have to apply it to each element.

![screen shot 2016-11-06 at 9 06 18 am](https://cloud.githubusercontent.com/assets/3920850/20039391/5d9bbf92-a400-11e6-8197-0471c228e790.png)


How would you feel about the second solution?

**Comment by mlaursen** [comment]
I actually don't think this is worth implementing as part of the base library since it is such a small style change after all the styling changes and the grid addition.
