### ISSUE TITLE
Menu/SelectField popup does not take care with viewport

### ISSUE THREAD

**Issue by albenik** [mlaursen/react-md#145]
Even if SelectField placed at the bottom of viewport and have no space bottom but large space on top, nevertheless it opens to bottom to offscreen.
User have to scroll page down to view the whole menu.
If SelectField place at the bottom of page, after opening the menu page vertical size increases, and after closing the menu page size goes buck to normal making page scroll jump.

**Comment by mlaursen** [comment]
This one is going to take some time for me to figure out. A quickfix would be to make it so that the window scrolls so that the `toggle` component is at the top of the screen. This would be similar to how mobile devices handle the initial keyboard open (scrolls text field to top of page and then displays keyboard). I feel this is a dirty hack and won't be reliable when there are many scrollable areas. However, this might be necessary for autocompletes since it would be weird to have the menu appear above the text field.

Another possibility would be to have the menu be a fixed element on the page instead of wrapping the menu in a small container (to position relatively). This is how I believe material-ui implemented their menus. The only thing I do not like about this is that it seems sluggish if the user scrolls with a menu open.

I'll think about this some more.

**Comment by mlaursen** [comment]
Here is a video of the current status of keeping items in viewport (looks like gif was cut short):

![alienatedscratchyalaskanhusky](https://cloud.githubusercontent.com/assets/3920850/23524372/979471e2-ff47-11e6-8075-b6c9ce14a66a.gif)

It isn't 100% perfect yet since it is supposed to attempt to swap vertical/horizontal positions when it reaches the viewport (it did actually swap it, but it still closed for some reason), and it does not attempt to swap positions when inside a scrolling container that is not the window.
