### ISSUE TITLE
Improperly rendered components/styles on page reload

### ISSUE THREAD

**Issue by andrelevi** [mlaursen/react-md#177]
Hi, everytime I reload the page, I get a brief flash of this:

![react-md_broken-styles](https://cloud.githubusercontent.com/assets/5660708/21273294/b6833ca2-c377-11e6-8118-ef222b507871.png)

Someone on HN had a similar complaint. I'm on OSX, and I see the issue on both Safari and Chrome.

**Comment by mlaursen** [comment]
This is really because I am using WebFontLoader to load the material-icons and Roboto fonts instead of just putting the CDN link in the `<head>`, so links are only added after initial page load. Also since my styles are split by webpack, some page's CSS is dynamically loaded after the initial render.

I am currently working on updating my documentation server to fix these errors to optimize the CSS delivery. I came from a JEE environment, so SSR is still a bit hazy for me.

**Comment by mlaursen** [comment]
Ok, it has been fixed and the website was updated.
