### ISSUE TITLE
Switch onChange is fired twice when clicking/touching the Switch's Button

### ISSUE THREAD

**Issue by CombatCode** [mlaursen/react-md#182]
Why sometimes clicking on Switch button onChange is fired two times ?

**Comment by mlaursen** [comment]
That is because I wanted the switch to be toggle-able by both clicking on its _track_ and having keyboard accessibility to press the enter key when focusing the button. However, I forgot about event propagation if you touch or click the button itself.

I have a fix that I can push up later this weekend.
