### ISSUE TITLE
DataTable should have to option to not include Checkboxes as the first column

### ISSUE THREAD

**Issue by frol** [mlaursen/react-md#195]
Passing `plain` to DataTable with Checkboxes in rows I am getting:

![broken-table](https://cloud.githubusercontent.com/assets/304265/21424941/bebb9d66-c84e-11e6-89f4-6b583fd72a9b.png)

Without `plain` my table looks nice, but I don't need those checkboxes on the left:

![normal-table](https://cloud.githubusercontent.com/assets/304265/21424942/bebc2fba-c84e-11e6-8c4b-540f3977e62a.png)

P.S. Oh my god how brilliant is this project! It is a lifesaver! Thank you so much!

**Comment by mlaursen** [comment]
The extra padding actually comes from the fact that when it is a plain data table, it assumes it will just be text. I might need to fix that. Basically all `.md-table-column--data` get [these](https://github.com/mlaursen/react-md/blob/release/1.0.x/src/scss/components/_data-tables.scss#L103-L109) styles applied. Eliminating the padding on your checkbox columns should fix the sizing issue.

I guess what I should do is add a new prop `selectable` || `injectCheckboxes`? (or some better name) that is `true` by default for legacy support. The checkboxes would only be added to tables if the table is: `!plain && selectable`

**Comment by frol** [comment]
That makes sense to me. I will be happy with any solution you come up with, I trust you!

**Comment by mlaursen** [comment]
Depending on how I see this, it might have to be delayed until `v1.1.0` if following SemVer. I could either see it as a new feature which requires a MINOR bump, or a bugfix. Not sure yet. I would prefer to put it in the `v1.0.1` patch if possible since `1.1.0` is going to be a bit down the road.

Soo, your vote: Feature or bugfix? :)

**Comment by frol** [comment]
I think, it is a feature, even though it is small (yet very useful for me). I am just prototyping my app, so I can wait for a proper fix released with the next update. Thank you!)

**Comment by mlaursen** [comment]
## Feature Request Information:
Currently, the only way to create a table without the insertion of a checkbox is to pass the `plain` prop. However, a `plain` table is really used for not enforcing the height limits and the `white-space: nowrap` enforced in a _data_ table. This ruins the styling of any selection controls, edit dialog columns, and select field columns that appears in the `plain` table.

### Suggested Solution
The `DataTable` component should be updated to have a new prop: `selectableRows` that defaults to `true`. When rendering a row, the `TableRow` component will only inject the checkbox when `!this.context.plain && this.context.selectableRows`.

This will allow for the _data_ table's styles to still be in effect.

### Suggested Solution - Alt
Since there is a `.md-table-column--plain` class name created, it might be better to remove the the styles that force the `.md-table-column--data` to look like a plain column when in a `.md-data-table--plain`. [Referenced Code](https://github.com/mlaursen/react-md/blob/v1.0.0/src/scss/components/_data-tables.scss#L237-L247). The `TableColumn` could then have a `plain` `prop` and `context` that would automatically apply the plain class name. The `props` would have a higher precedent over `context` -- if `props.plain` is defined, use whatever value over `context.plain`.

```
cn({ 'md-table-column--plain': getField(this.props, this.context, 'plain') });
```

This would allow all columns to automatically be set to `plain` when in a `plain` table, and allow the developer to disable the `plain` styles on specific columns.

Or maybe both of these solutions should be included. :man_shrugging:
