### ISSUE TITLE
[STICKY] - Showcase Apps Created with react-md

### ISSUE THREAD

**Issue by mlaursen** [mlaursen/react-md#196]
I really need some other apps I can showcase on the documentation website. I don't believe the documentation website is a good example for mobile devices since a lot of the heavy lifting is still done on the client (Multiple app examples on a page, pulling in large amounts of source code, and converting/rendering the code to markdown on the client).

As long as your app doesn't seem sketchy, I'd be happy to advertise it by having a Showcases link in the Discover More section. If this appeals to you, supply the following to me via this issue or my email:

- **Project Name**
- **Author/Organization**
- **Link**
- **Description**
- **Logo/Screenshot** (356x200 ideal)

**Comment by sniphpet** [comment]
Hello,

First of all thank you for your amazing work on that framework.

- Project Name : Les Passions de Peronnes
- Author : [me](https://github.com/sniphpet)
- Link : [Les passions de peronnes](https://bredariol.be/product)
- Description : Wine reseller. The work is still in progress, but you can already get an idea. All the others part of the application will be migrated to react-md.
- ![logo](https://cloud.githubusercontent.com/assets/5574267/24578546/578c1b10-16e2-11e7-9d07-128cd9149c48.png)

All the back office is built using react-md. I can host a demo version if you are interested as well.

**Comment by mlaursen** [comment]
Thank you, glad you like it!

Nice site! I'll get started on making the Showcases page and have this on there with the release of `1.0.12`

**Comment by fkhadra** [comment]
Hello @mlaursen,

Now everything is built using react-md. Could you update the link https://bredariol.be/ instead of https://bredariol.be/product.

The old one redirects to the JSON API.

The app use mobx, react-router. I could check if I can open source the code.

**Comment by mlaursen** [comment]
Sure thing! I just triggered a build with the change, so it should be live within 10 minutes or so.

**Comment by fkhadra** [comment]
Thanks appreciate !

**Comment by phlare** [comment]
Hi!   we've been super happy with react-md for the most part and I'm looking to get into contributing a bit as well.   We've built our full product using it quite extensively on top of an Elixir/Phoenix API.
note: the marketing site that you see at the root of hostfully.com is NOT using react-md (yet) but the product demo at https://v2.hostfully.com/california-dreaming is.

thanks again for all your work on this framwork. 

(we're also working on building an attributions page and would like to link back to you as well)


Project Name:  Hostfully.com

Author/Organization:  [Hostfully](https://github.com/hostfully)

Link: https://hostfully.com   (product demo: https://v2.hostfully.com/california-dreaming)

Description:  Hostfully is a content generation and guest communications platform built for vacation rental management companies. Using Hostfully, managers upload property-specific content and local recommendations that travelers can use while they are at the destination. Companies also use Hostfully as a channel for guest communication – instead of overloading guests with too many details about the property, managers direct their guests to well-structured content in each property’s customized online guidebook – accessible on mobile, desktop, and in print.

![07e6e296-desktoprecommendations_0bu06q0bu06q000000](https://user-images.githubusercontent.com/692484/36882479-64ce426a-1d91-11e8-8649-84a625880132.png)

**Comment by zachsa** [comment]
Hi - I subscribed to the repository recently, as like others I really appreciate and love the component library you have made available to us. Would it still be possible to list a site as an example?

The web application is still a work in progress, viewable at seacrifog.saeon.ac.za. Ideally it will be stable by end February
