### ISSUE TITLE
Reducing path naming and singularity

### ISSUE THREAD

**Issue by renshenhe** [mlaursen/react-md#218]
Like to break many current builds but possibly in future versions to reduce import/require paths similar to:
```js
import Avatar from 'react-md/Avatars';
```
I have done so in personal libs by adding a script to copy files to a cleaner directory in a prebuild but there are possibly much better methods.

Also what are the intentions of plurality of component directories that implies multiple variants? e.g.
```js
import Button from 'react-md/lib/Buttons'
```
Despite Buttons no longer having multiple variants.

I understand there is:
```js
import Button from 'react-md/lib/Buttons/Button'
```
though this mandates more typing with no gains.

I have no qualms with components pertaining to parent components under singular naming e.g `ListItem` for `List` and `Tabs` and `TabContainer` for `Tab` as they ultimately belong to a single component.
```js
import Tabs from 'react-md/lib/Tab/Tabs'
import TabContainer from 'react-md/lib/Tab/TabContainer'
```

This also draws my attention to possibly renaming `Tabs` to `TabsBar` for better clarity?

I assume the plurality of the component folders might be related to doc-gen for the doc site but haven't delve too deep into the details for it and hopefully not a significant oversight.

**Comment by mlaursen** [comment]
I personally prefer the pluralization instead of singularity. It makes logical groupings of related components and future-proofs components down the road if more related components are added to the spec. I also like the consistency; when you import from a pluralization, you have access to all the components:

```
import { Tabs, TabsContainer, Tab } from 'react-md/lib/Tabs';
```

but if you specifically choose a singular, you only have access to a single component.

```
import Tab from 'react-md/lib/Tabs/Tab';
```

I know it is a lot of typing for `import x from 'react-md/lib/Xs'`, but this is completely optional and only required if you aren't using every component in your app.

```
import { Button, Tabs, TabsContainer, Tab } from 'react-md';
```

is completely valid (which probably is what you should do if you want to use the CDN for prod).

The only reason you need to specify `import Button from 'react-md/lib/Buttons/Button';` at this time is for the few people that were using this before my major rehaul and 1.0.0 release. `import Button from 'react-md/lib/Buttons';` does the same thing, but it still bundles the deprecated `IconButton`, `FlatButton`, `RaisedButton`, and `FloatingButton` components. In the next major release, those components will be removed so you no longer need to only import `'react-md/lib/Buttons/Button';`

This could all be moot too if you use webpack2's tree shaking and #205 gets completed.

I do think it might be good to rename the `Tabs` component to `TabsBar` or something else. It isn't really a self-describing name at the moment.

**Comment by mlaursen** [comment]
Something I was attempting for this project was naming consistency and the pluralization felt better to me. If the overall consensus is for singularity, I would be happy to move over to that.

The other touch points would be the fine name for every component's styles to be singular as well as update and deprecate every variable, function, and mixin for components to be be singular.
