### ISSUE TITLE
FontIcon forceSize does not also update the fontSize

### ISSUE THREAD

**Issue by ksmithut** [mlaursen/react-md#221]
I'm using react-md 1.0.1 with Material icons, here is what I'm using.

```js
<Button
  icon
  forceIconSize{16}
>settings</Button>
```

I'm expecting the icon to be 16px wide/tall, but it's still the 24x24px size. I do see that the generated `<i>` tag has an explicit style with my desired 16px tall, but the `.md-icon` class has a `font-size: 24px` style applied to it, which forces the size of the icon to be 24px regardless of the width/height of the element.

Really what I want is to be able to change the size of the entire button, but that seems to not be possible just using proptypes. As a workaround, I'm applying styles and classnames to customize the size, so feel free to close this as "won't fix" if it's working as designed.

**Comment by mlaursen** [comment]
Yea, right now the `forceIconSize` (Button) and `forceSize` (FontIcon) are really used for setting the width and height of icons because other font icon libraries like FontAwesome and some weather icons do not have consistent square shapes.

I guess I could update the forceSize to also update the fontSize so the resulting styles are `{ width: size, height: size, fontSize: size }`, but I haven't checked the results of other font icon libraries yet.

I'll think about this a bit more, but I think it is reasonable to either update the font size via the style prop: `style={{ fontSize: 16 }}` (FontIcon) or with your custom className (Button) like you are doing.
