### ISSUE TITLE
Ink focus effect intentional when switching focus?

### ISSUE THREAD

**Issue by renshenhe** [mlaursen/react-md#222]
If a component, for example, `<Button />` is clicked and focus is switched to another window then back to the window with `<Button />` an ink component is created with state of focus.  I am unsure whether this effect is intentional to remind user of their last focused action or unintentional results.

To run an example open browser with a component with an ink effect and another app/browser side by side, click the component with ink effect then switch focus to the other window and back.

**Comment by mlaursen** [comment]
This is a bug -- related to #172 

Ink is triggered on the focus event instead of `onKeyUp` so that it can be triggered without direct access to an inked component. This is mainly used the the SelectField, Autocomplete, and Dialog components so that the UP/DOWN arrow keys trigger the ink correctly in the appearing list, and when a dialog closes, the element that triggered the dialog gets focus again (and displays the ink).

I  do need a better solution for this though.
