### ISSUE TITLE
Re-evaluate the grid system and sizing mechanisms for components

### ISSUE THREAD

**Issue by davidagee** [mlaursen/react-md#223]
I'm not sure if this is the right place to put this, but I'm not sure what other channels for communicating with the author are available.

I was wondering if you'd given any thought wrt your decision to use `box-sizing: content-box` in conjunction with `calc` sizing throughout the project. As I'm sure you're aware, most popular grid systems (eg. Bootstrap, Foundation) use `border-box` which removes the need for `calc` in most places and makes the grid system a lot easier to work with - you don't need to create nested DOM elements for simple padding and margins. 

I'm not sure if this is an authoring decision or something that comes directly from the material design spec, but if the former, it may be worth giving some thought to an alternative approach.

**Comment by mlaursen** [comment]
I'm actually using [box-sizing: border-box](https://github.com/mlaursen/react-md/blob/master/src/scss/_typography.scss#L430-L437) instead of `content-box`. The main reason for `calc` in the grid is because of the material design spec for margins between cells. I don't really know a better way to get correct width sizing without doing `calc` for that. When using `.md-grid--no-spacing`, `calc` is not involved. I would be happy to hear other solutions for the margins.

**Comment by davidagee** [comment]
Ah, ok. It seems like there's a bug, how are you globally applying `border-box`? When I inspect any react-md components in Chrome, the calculated `box-sizing` value is `content-box`. When I apply a global override of `html * { box-sizing: border-box; }` the components are not rendered correctly (eg. buttons). I will take a look this evening to make sure it is not something related to my application and close this issue if that's the case.

**Comment by mlaursen** [comment]
It is included with the `react-md-typography` mixin (which is probably a bad place to put it), so if you aren't including that, it would not appear. It appears to be in the CDN dist as well.
