### ISSUE TITLE
Suggestions for improvements

### ISSUE THREAD

**Issue by MrXyfir** [mlaursen/react-md#233]
First of all, many thanks @mlaursen for creating and maintaining this project. I've switched over from Material-UI and am very happy so far, but there are a few things I'd like to see improved:

*****

# SelectField

## Children

It would be nice to have the ability to instead of using the `menuItems` property to instead pass them as children to `SelectField`.

```jsx
<SelectField menuItems={itemsArray} />
<SelectField>{itemsArray}</SelectField>
```

You could support both at once but prefer `props.children` over `props.menuItems` or the other way around if needed.

## Uncontrolled State

While the component doesn't require `value` and can handle state on its own, there's no (supported) way to get the value without listening for changes. It would be nice to have proper support for this under a `getValue()` method or something similar without having to use `this.refs.selectField.state.value`. It doesn't make it much shorter but I think it does make it clearer and also future-proofs against any changes to the structure of the component's state.

Maybe `get` could be used to return the value: `get value() { return this.state.value; }`.

```jsx
<SelectField ref="sf" />

this.refs.sf.state.value // current, unsupported way
this.refs.sf.getValue() // new way
this.refs.sf.value // even better
```

# Button

Like `SelectField`, instead of requiring the button's text to be passed under the `label` prop, also accept it as a child. Also like `SelectField`, both could be supported with a preference for `props.children`

```jsx
<Button raised primary label="Submit" />
<Button raised primary>Submit</Button>
```

Now obviously there's a conflict there due to icons but personally I'm not a huge fan of putting the icon name as an element's child text. I think that would be better off in its own property. Any chance of this getting changed?

# All Inputs

As mentioned earlier for `SelectField` in regards to the `this.refs.field.value` interface, it would be nice to apply this same system to all input components. `getField()` exists for `TextField`, which is nice, but 99% of the time you just want the value.

# SvgIcon

A good example for an `SvgIcon` component can be found in Material-UI:

http://www.material-ui.com/#/components/svg-icon

Just a simple component that you can pass SVG data to.

*****

I have no problem implementing some or all of these features myself and making a pull request so long as I know you'll accept it. Is there anything in here that I've mentioned that you would accept?

**Comment by mlaursen** [comment]
Thanks, I'm glad you are liking it so far! Here are my thoughts about the suggestions:

### SelectField
I personally do not like passing things as `children` that should not be directly rendered in the component. What I normally consider valid are `string`, `number`, `element`, or `arrayOf` those types. What is the reason you'd prefer the `menuItems` as `children`?

### All Inputs
I actually haven't done much work with stateless components, but I do agree, it would be much nicer to be able to say `this.refs.select.value`. So the components that would need to be updated are:
- `Autocomplete`
- `SelectionControl` (`SelectionControlGroup`)?
  - these should probably also expose the `checked` value.
- `SelectField`
- `TextField`

### SvgIcon
I have been thinking about doing SvgIcons for awhile, but I haven't worked with them too much so I don't know their full behavior. I am normally not a fan of doing InlineSvgs since they are not cacheable or reusable. I think the `<use x:path>` (can't remember fully what it is) might be the solution to that. However, I believe you can no longer style the SVG that way? I'd be happy for suggestions here.

### Button
Yeah, I understand the concerns here. I set it up this way because I considered the main use case of the button is some `label` string to be applied. The icons were the biggest thing because I don't know how many users use different font icon libraries. And since it is still possible to render SVGs in the `FontIcon` component, I thought it would be better to have all that in the `children` instead of an `iconChildren` prop.

It does seem a lot more semantic to say `<Button primary raised>My Button</Button>` instead of `<Button primary raised label="My Button" />` since it is closer to the native `<button>` usage. The migration for this might be a bit tricky.

**Comment by MrXyfir** [comment]
# SelectField / inputs

> I personally do not like passing things as children that should not be directly rendered in the component. 

I figured this was the case. The reason I would prefer this is because it would be similar to how the native `select` and `option` elements work. As you can probably tell most of my suggestions are related to making the components act how a normal html element or React element would work.

# SvgIcon

When it comes to SVG icons, I actually don't know too much about them either. Up until now I've always used font icons but after reading an article somewhere about the benefits of SVG icons over font icons and how GitHub uses only SVG icons, it has been on my radar and my next project will probably utilize them. Once I get some experience with them I'll be able to give some proper suggestions.

From what I know, I assume `<symbol>` with `<use>` is probably the best way to go. The symbols could be created elsewhere and be loaded in its own file while the component takes the symbol name `<SvgIcon icon="icon-name" />`  as most likely its only required property.

# Button

As much as I'd like to see `label` moved to `children`, I understand that it would be a breaking change. As for icons, maybe the button could also accept those as children? This would obviously require even more changes.

```jsx
<Button raised primary>
    <FontIcon|SvgIcon ... />Submit
</Button>
```

This is similar to how I would normally use an icon in a button with a normal button element.

```jsx
<button>
    <i class="icon-submit" />Submit
</button>
```

**Comment by mlaursen** [comment]
### Button
I am thinking that the `label` will be replaced as `children` and the current `children` will be replaced as `iconChildren`. My reasoning is that I still think there should be a nice way to use the `IconSeparator` that exists in the `Button` when there is both a label and an icon; but it is still optional. This would allow:

```js
<Button raised primary iconChildren="close">Close Me!</Button>

// and
<Button raised primary>Close Me! <FontIcon>close</FontIcon></Button>
// Could still use the IconSeparator manually here as well if you want.
```

I think I have a decent idea for handling migration on this now, the main problem is the support of text buttons and the icon/floating buttons since they are all the same component.

### SelectField / inputs

> As you can probably tell most of my suggestions are related to making the components act how a normal html element or React element would work.

Yeah, I think that is a good idea. If the `menuItems` were a list of `option` or `ListItem`, I think passing them as `children` would be the way to go. I think I _should_ probably update the select field to allow the `children` as a list of `option` and convert those into the `ListItem` component. Does seem a bit roundabout though.

**Comment by MrXyfir** [comment]
# Button

I like that idea.

# SelectField

I also like that idea. I don't think it's necessary (although I don't think it'd be bad) to accept `option` elements and convert them to `ListItem`, so long as `SelectField` can accept `menuItems` as `children.`

**Comment by mlaursen** [comment]
Everything except for the `SelectField` changes should now be in 1.1.0 so going to close this for now. The proposed `SelectField` changes have been added to the #493 to be added at a later time.
