### ISSUE TITLE
SelectField should select an option when a key is pressed

### ISSUE THREAD

**Issue by carlosforero** [mlaursen/react-md#25]
SelectField should have a behaviour similar to an html control selection, so when the control has the focus and a key is pressed, the control should select the option that starts with the character pressed.

**Comment by mlaursen** [comment]
That sounds reasonable to me. It looks like I am also missing some other key events which should be fixed as well. It looks like in one of my `ListItem` updates, I accidentally removed the tabIndex from these items so you can't even tab through the items.

So the things needed to fix this would be:

- Select an option when a letter key is pressed
- Enable tabbing through items
- Autofocusing first element or selected item when select field is open (undecided)
- Enable the up/down arrows to navigate through items

**Comment by carlosforero** [comment]
About the issue:
* Enable tabbing through items

I think the navigation through the items should be only with up/down arrows. Because the Tab key is to navigate through entire Field controls, and the List Items belongs to the entire SelectField control. Therefore the Tab key in SelectField should be as an Enter key but moving to the following entire control in the form.

I know that the list of items is rendering with a Menu and ListItem controls inside, so when the ListItem is for the purpose of a static menu, pressing the tab should capture the focus of the menu item. So, I think the solution could be a true/false property in ListItem, called for example: "tabstop".

**Comment by mlaursen** [comment]
There is different behavior on the html `select` tag between browsers and OS. Great stuff. After playing around, I do agree that tab should **not** be used to navigate through items.

I think that the behavior should be as follows:

- User tabs focus onto the unopened select field
    - User can press the `down` key to select the next item in the `menuItems` (if it exists)
    - User can press the `up` key to select the previous item in the `menuItems` (if it exists)
    - The menu is not opened for these two events
- User presses `enter` or `space` to open the menu
    - Currently selected item has focus
    - Same `up` and `down` key press logic.
    - User can press `enter` or `space` to select a current item which closes the menu and adds focus back to the unopened text field
    - User can press `tab` to select the current item which closes the menu and adds focus to the next focusable page element.


I am not entirely sure if the `ListItem` component itself should have a `tabstop` prop or if the component using the `ListItem` should handle the `onKeyUp` listener for preventing a next `tab` key.  I am leaning a bit towards having the component using the `ListItem` to manage the `onKeyUp` listener because I think the general behavior of the `List`/`ListItem` component would be that you can tab through them. I am not sure where the correct place for that logic would be yet.
