### ISSUE TITLE
Menu/MenuButton not displaying properly when there is only one ListItem

### ISSUE THREAD

**Issue by irvinlim** [mlaursen/react-md#259]
### Description
Menu/MenuButton is not displaying the menu properly when there is only one ListItem.

### Images/Screenshots
<img width="353" alt="screen shot 2017-02-17 at 4 27 34 am" src="https://cloud.githubusercontent.com/assets/9884746/23039701/7206fdce-f4c9-11e6-9128-726e70f8b40d.png">

*Not displayed properly when there is only one item.*

<img width="213" alt="screen shot 2017-02-17 at 4 28 14 am" src="https://cloud.githubusercontent.com/assets/9884746/23039718/8590322a-f4c9-11e6-898b-62dbf9f2efbc.png">

*Displays properly with two items.*

### Link to a gist or code sample where the issue can be reproduced
https://codepen.io/irvinlim/pen/MJRXPB?editors=0010

### Version
- React: 15.4.2
- React-MD: 1.0.5 (wasn't working in 1.0.1 either)

**Comment by MrXyfir** [comment]
Wrap it in an array.

```jsx
<Menu isOpen id="test-1" onClose={ () => {} }>
  {[<ListItem primaryText="Undo" />]}
,/Menu>
```

**Comment by mlaursen** [comment]
When there is only a single child, it assumes that the child is the `List` component, and does some additional prop injections. I went with this assumption because I didn't think a single item list was very helpful. I needed this for some behind-the-scenes work for components that use the `Menu`. I _could_ expose a new prop `menuProps` or something else at some point so this isn't needed, but I think right now you should either manually wrap your single `ListItem` with a `List`, or in an array.

**Comment by irvinlim** [comment]
Okay. Is it better to check the type of the child node if it matches `List`, if it is a single child? Because right now it is not immediately clear to users that a single child should be a `List`, and instead it looks pretty buggy when I first encountered it.

Otherwise, perhaps we should update the docs first to inform users of this behaviour, until you find a better way around it.

**Comment by mlaursen** [comment]
I'll make sure to get this ether documented better or update my internal usage
