### ISSUE TITLE
SelectField menuItems as Component

### ISSUE THREAD

**Issue by ferpintado** [mlaursen/react-md#262]
Is there a way to render a components as a menuItem? I am trying to add a picture beside the menuItem.

Any idea of how can I get this working?

Thanks

**Comment by mlaursen** [comment]
Since the `menuItems` get mapped into `ListItem`, you can define your menu item shape to include `ListItem` props.

```
const menuItems = [{
  label: 'Item With a Picture',
  value: 'item-1',
  leftAvatar: <Avatar src={image1} alt="A description of image 1" />,
}];
```

if the `ListItem` component doesn't suit all your needs, you can also go with the custom component implementation of the `ListItem`
```
menuItems = [{
  label: 'Item with a Picture,
  value: 'item-1',
  component: ListItemPicture,
  ... any ListItemPicture related props ...
}];
```

As long as your custom component doesn't share the same props as `ListItem`, it _should_ work.

**Comment by ferpintado** [comment]
Thanks for your response.

It worked nicely.
