### ISSUE TITLE
draggable lists :enhancement

### ISSUE THREAD

**Issue by wdiechmann** [mlaursen/react-md#269]
If I understand your ListItem.js correctly, one small change would make it a lot easier to build

`export default class DraggableListItem extends ListItem {}`

In the ListItem.js you have

```
    return (
      <li
        style={style}
        className={cn('md-list-item', {
          'md-list-item--nested-container': nestedItems,
        }, className)}
        ref={this._setContainer}
      >
        <AccessibleFakeInkedButton
          {...props}
          __SUPER_SECRET_REF__={this._setTile}
```

and by _using_ the `{...props}` for the `<AccessibleFakeInkedButton />` you cannot further specialize the component. 

I propose to let the ListItem be all about standard `<li>` and have the `{...props}` added to the `<li>`

**Comment by mlaursen** [comment]
This _might_ work. I might need to update the documentation a bit and hopefully give some better migration warnings. The current ListItem looks like [this](https://github.com/mlaursen/react-md/blob/release/1.1.x/src/js/Lists/ListItem.js#L482-L491).

It might be that a new prop `itemProps` is added instead. One of the main reasons for passing all the remaining props to the `AccessibleFakeInkedButton` is so that the following is possible:

```
import { Link } from 'react-router';

...

<ListItem primaryText="Some Route" component={Link} to="some-route" />
```

Another possibility is to just extract any of the event listeners and apply them to the `ItemComponent` instead of the `AccessibleFakeButton`. I think it'll just take some testing.

**Comment by wdiechmann** [comment]
i'll be happy to bend over - testing it :)

**Comment by wdiechmann** [comment]
hmmm - I see that most components extends the PureComponent -

Another way out might be extending whatever components, where draggable makes sense, from DraggableComponent (which then itself would extend PureComponent - and add special properties to that component - something like

```
// this class does all kinds of crazy stuff like binding etc
export default class MDBaseComponent extends PureComponent {
  _bind(...methods) {
    methods.forEach((method) => this[method] = this[method].bind(this));
  }
}

export default class EventedComponent extends MDBaseComponent {

    onDragStart(e) { this.props.onDragStart(e) }
    onDragEnd(e) { this.props.onDragEnd(e) }
    onDragOver(e) { this.props.onDragOver(e) }
    //
    // actually - every event could be 'assigned' ready for some 
    // 'up the three' class to exploit it :)

}

export default class ListItem extends EventedComponent {}
export default class OtherComponentLikeCardPerhaps extends EventedComponent {}

```

**Comment by mlaursen** [comment]
Ahh, one thing I would like to mention is that I would like to go with a more functional approach here with composition instead of inheritance. I would like these to be higher order components. Facebook did a good write up about the reasoning for HOC [here](https://facebook.github.io/react/docs/higher-order-components.html).

**Comment by wdiechmann** [comment]
I fail to see how the HOC will be able to output 

``` <li draggable=true onDragStart=something etc> ```

without _rewriting_ the ListItem component (which is advised against in the Facebook post ?

**Comment by mlaursen** [comment]
The first fix of this issue would be to expose props correctly to the surrounding `li` component like you first mentioned in this ticket. It is really a problem with my library that needs to be addressed before the draggable enhancement can be done

**Comment by mlaursen** [comment]
I'm going to close this one in favor of #439

**Comment by sachiner** [comment]
No to working with react router link

using same as @mlaursen mentioned

<ListItem
        component={Link} 
        to="/payments/Dewa"
        leftAvatar={<StarIcon/>}
        rightIcon={<InfoIcon />}
        primaryText="Dewa"
        secondaryText={"Jan 17,\n 2014"}
        threeLines
        
      />
