### ISSUE TITLE
[TextField] - Better TextField number support

### ISSUE THREAD

**Issue by maxcan** [mlaursen/react-md#280]
### Description

Numeric `TextField`s don't render properly if you set their value to `undefined` for example, to show an empty field after a submit:

Before submit, looks good:
![image](https://cloud.githubusercontent.com/assets/646732/23645482/264d8848-02c1-11e7-9349-20acd74f1a52.png)

Afterwards when the `value` is correctly set to undefined:
![image](https://cloud.githubusercontent.com/assets/646732/23645471/16453518-02c1-11e7-882f-20561407296a.png)

### Version
- React 15.4.2
- React-MD 1.1.x

**Comment by wdiechmann** [comment]
from http://materializecss.com/forms.html#input I remember that it is a "CSS-thing" - whether you could fix it that easy with react-md is beyond me (yet) :)

**Comment by mlaursen** [comment]
Yeah, the same thing can be accomplished by providing `floating` to your text field; it will make the label float. However, this might be something that should be handled by my component.

I have a couple of questions about the current flow:
- When you set the value to `undefined`, are you setting it by the `value` prop or something else?
- Have you tried setting the value to the empty string or `0` instead of `undefined`? (I think that might work out of the box)

**Comment by maxcan** [comment]
Value prop. Can try empty string

**Comment by maxcan** [comment]
Oh, also the empty string is a bit of a hack since its a numeric field..

**Comment by mlaursen** [comment]
Ok, cool! I think I'll be implementing better text field number support in an upcoming release after the feedback I've gotten. The native `input type="number"` is pretty terrible, so it'll be good to update my component to fix some of those issues.
