### ISSUE TITLE
Since v1.0.8 Drawer automatically opens

### ISSUE THREAD

**Issue by pferdone** [mlaursen/react-md#291]
Right now the drawer automatically opens for desktop sized application, if you provide a toggle function for **onVisibilityToggle**. As far as I can tell and by looking at the stack trace **_updateType** seems to be responsible for that. I had to go back to **v1.0.6** to work around the issue.

```javascript
toggleDrawer = (visible: boolean): void => {
  this.setState({ visible });
}

<Drawer
  visible={visible}
  position="left"
  onVisibilityToggle={toggleDrawer}
  type={Drawer.DrawerTypes.TEMPORARY}
  style={{ zIndex: 100 }}
/>
```

_**EDIT**_
This behaviour can actually be seen in the examples
https://react-md.mlaursen.com/components/drawers

**Comment by mlaursen** [comment]
Yeah, this can be _fixed_ temporarily by also providing `mobileType={Drawer.DrawerTypes.TEMPORARY} desktopType={Drawer.DrawerTypes.TEMPORARY}`.

This bug is coming from the fact that the `type` prop is really to make it up to the programmer instead of my drawer figure out which of the 7 types to use. So it defaults to visible because the current media drawer type of the drawer matches to `full-height` (which means the drawer should be open).

I can fix this bug by providing an extra prop `constantType` which defaults to `true`. If the `type` prop is defined and one of the temporary types and the `constantType` prop is `true`, I will use the `type` prop for determining the current media's drawer type instead of the `mobileType`, `tabletType`, and `drawerType`.

**Comment by nbolten** [comment]
This issue is affecting me on v1.0.15. I set an app-level state for drawer visibility, pass it to Drawer as the `visible` prop, and set onVisibilityToggle to a method that sets state to whatever the `visible` value is.

To replicate: https://codepen.io/anon/pen/eWwdYP

I'm not totally sure what is supposed to be done with onVisibilityToggle, but it's required if you set the `visible` prop. If I set it to a function that does nothing, everything appears to behave as expected - no default visibility, toggling still works, etc.

Am I using the wrong pattern for onVisibilityToggle, or should the issue be reopened?
