### ISSUE TITLE
Data Table Check boxes are not set correctly when a row is removed programmatically (state, redux, etc...)

### ISSUE THREAD

**Issue by jbetancur** [mlaursen/react-md#297]
## Description
https://codepen.io/johnnyazee/pen/xqdoZR?editors=0011

### Issue 1
- Select the first item 'test1'
- Click on the 'Remove Item' for 'test1'
- and so on...

### Possible related Issue 2:
When the table loads you will initially notice the header select all box is checked briefly then unset.  If you have 0 items then the select all box is always selected.

I've tried debugging this myself so I could submit a PR fix, but to be honest I haven't had much time this week.

### Version
- React latest
- React-MD 1.0.7

**Comment by mlaursen** [comment]
This one will actually take awhile to fix since I hadn't thought about dynamic rows when making this (huge mistake). I am going to push it back to either 1.0.10 or 1.1.0 since I need to get the drawer fixes out.

**Comment by mlaursen** [comment]
Just a note to myself when I start this ticket.. This should probably update the list of selected state from the `componentWillMount` and `componentWillUnmount` on the `TableCheckbox` component which would solve most of the problems here instead of manually initializing it by counting the number of rows in the table. Not sure why I did it that way in the first place..

**Comment by jbetancur** [comment]
Thanks @mlaursen - just confirmed and works perfectly!

**Comment by mlaursen** [comment]
Great! Glad to hear.
