### ISSUE TITLE
Create a Slack Group

### ISSUE THREAD

**Issue by carlosforero** [mlaursen/react-md#30]
I think it would be a good idea to have a Slack group for this project in order to improve communication.

**Comment by mlaursen** [comment]
I think that is a fantastic idea.

I hadn't actually set anything up yet (real work flow, groups, contributing info) because I hadn't thought anyone was using this library since I haven't done a _real_ release. I guess this is a good time as any to get everything rolling since the `v0.1.0` _real_ release is coming close.

I thought I knew what I was doing and created a group at https://react-md.slack.com, but not entirely sure how to create a public group yet. I'll check back on it later (or if you know how).

**Comment by carlosforero** [comment]
I thought Slack allowed to create a public group, but only is possible to create a solution using the Slack API. There is an app https://github.com/outsideris/slack-invite-automation, but needs hosting and configuration.

An alternative is to send invitations to active contributors, another alternative is https://fleep.io which allows create a chat group with a public url.

**Comment by mlaursen** [comment]
I like the idea for the slack-invite-automation. I will set that up later this week and get that rolling!

**Comment by mlaursen** [comment]
I went with creating a gitter instead.

https://gitter.im/mlaursen/react-md

Once I update the documentation website with a link to here, I will mark this ticket as done.
