### ISSUE TITLE
Ajax Autocomplete Flashing

### ISSUE THREAD

**Issue by mctep** [mlaursen/react-md#330]
### Description
Suggestion list is flashing when `data` property is being filled after empty state.

### Images/Screenshots
![out](https://cloud.githubusercontent.com/assets/1949681/25001184/9322783e-2044-11e7-96be-31e217a1d688.gif)
### Version
v1.0.11, v1.1.x
https://react-md.mlaursen.com/components/autocompletes
Google Chrome

**Comment by mlaursen** [comment]
This problem arose because my autocomplete component set the visibility to `false` for the menu, and after it finally fetched the data from spotify, it set it back to `true`. But this all happened so fast, that it gets that jumpy animation.

My fix was to make it so that if there is no `filter` prop (so using some ajax filter/search), the visibility will not be changed after each change in the input. Instead, the visibility will be changed when the `data` prop has been changed.

**Comment by mctep** [comment]
Hello! After that fix `ajax` autocomplete stops work. Only reblur helps.
![untitled](https://cloud.githubusercontent.com/assets/1949681/26213624/6b52fc64-3c02-11e7-8ef0-5d0009ddf34e.gif)
