### ISSUE TITLE
[TablePagination] - Can I use pagination without table?

### ISSUE THREAD

**Issue by lext-7** [mlaursen/react-md#355]
TablePagination is rendered as tfoot, but what if I want to use pagination without table ?

**Comment by mlaursen** [comment]
Right now it isn't possible since the only use case was for tables when I made it. I might be able to extract parts of it so it can be used outside of the table, but I'm not entirely sure yet. You might be able to just do `<table><TablePagination {...props} /></table>` which is probably the closest you can get to using it "_without_ a **full** table".
