### ISSUE TITLE
Make DatePicker readOnly

### ISSUE THREAD

**Issue by hisapy** [mlaursen/react-md#363]
As discussed in Slack, when given `readOnly` prop to DatePicker, the component should not let you pick a new date, or perhaps simply, just not open. Currently, it opens and you can also pick a new date.

```json
"react-md": "^1.0.13"
"react": "^15.4.2"
```
Tried this in  Chrome & Safari browsers.

Notice that the `readOnly` prop although not documented, **it works in TextFields**.

**Comment by mlaursen** [comment]
I will go with this behavior.. If the picker is `readOnly`, the value will be unchangeable and the picker will never appear. It will only display a formatted date in the text field. I'll update the picker to be openable via spacebar as well.

I will also apply the same logic for `TimePicker`s.

**Comment by hisapy** [comment]
Thanks @mlaursen

**Comment by davosolo** [comment]
@mlaursen What if I want to give my users the alternative of manually enter the date/time? Is there a way to do that in the component?

**Comment by hisapy** [comment]
@davosolo I'd do it by opening the DatePicker only when clicking on the icon and add a text mask to interact with the TextField. 

For the mask you might want to check https://github.com/text-mask/text-mask. I'm using it in a `CurrencyField` which is basically a react-md `TextField`.

**Comment by mlaursen** [comment]
I've also been working on a new `DatePicker` since my work started needing/using date and time pickers and the current `DatePicker` fails most user testing and discoverability. Unfortunately it no longer really follows the material design spec, so I'm not sure if it should be applied to this library. I _think_ it will be ok since I believe that most users of react-md are looking for usability and customization over just following the material design spec. We'll see when it's closer to finished.

This is what I currently have: https://gfycat.com/gifs/detail/MerryLivelyBluetonguelizard
It's getting close, but there is still a bit more polishing to go into it and some more user testing.

**Comment by davosolo** [comment]
Ok, I guess I'll try with @hisapy for now and see if I get it working with react-md correctly. Although I'm not sure on how to decouple the input text from the DatePicker component.

@mlaursen Looks great what you have so far... seems very functional. Keep it up.

Thanks both of you for the answers!
