### ISSUE TITLE
Discrete Slider gets wrong values/renders when min value is set

### ISSUE THREAD

**Issue by nbolten** [mlaursen/react-md#379]
### Description

If you set a min value for a discrete slider and drag the thumb pointer, it generates incorrect values - everything seems to be offset by the same value as `min`. In the example, setting `min={50}` makes the thumb pointer disappear from the minimum of the range to half-way down, and registers a value of 50 for that whole region. If you set `min=10` and drag, the thumb pointer keeps a value of 10 for ~1/9 of the range, though it also doesn't render during that first 10. In the example, the value restores to the correct version when the drag ends, but I've had it consistently reset to `max - 1` at the rightmost point in personal examples.

So, there's two issues here, but I think they're just one: the `min` value is producing some incorrect offsets somewhere along the line that messes up both the values and the thumb pointer render.

### Images/Screenshots

![screenshot from 2017-05-22 19-18-30](https://cloud.githubusercontent.com/assets/1947393/26335858/b4397ef2-3f23-11e7-95d3-c76c45b8affb.png)

### Link to a gist or code sample where the issue can be reproduced

http://codepen.io/anon/pen/XRoEqX

If you delete the `min={}` line, everything works fine. Setting `max` doesn't cause this issue.

### Version
- React
  - v15
- React-MD 
  - v1.0.14 (latest)
- Browser
  - tested on Chrome 58
  - tested on Firefox 53

**Comment by mlaursen** [comment]
Yeah, I think this was 2 things:

1. The defaultValue should be set to the `min` value instead of `0`. In your example above, it should have been complaining about that with prop type validation. This is what caused the initial wrong calculations.
2. The discrete slider's value was not keeping the scale in mind when determining if the value was "on", so it was invisible.

The fixes I added for this was to make the `defaultValue` prop optional and set itself to the `min` value if `undefined`. It will still warn you if you manually set a `defaultValue` that is not within the `min` and `max` and I consider that part a developer bug instead of this lib's bug.

The second fix will be to correctly make the slider's thumb "on" when the `min` value was set.

**Comment by nbolten** [comment]
This issue is still occuring in v1.0.15. Reproducible example: https://codepen.io/anon/pen/PmrGpj

Essentially, the whole slider seems to be 'shifted' by whatever the value of `min` is while being dragged, but then registers the accurate value after the drag stops. Specifically:

### While dragging:
1. While the `max` is set to `10`, the maximum value reported on the thumb is 8 (i.e. offset by the `min`, which is 2). This is the actual value passed to onChange, as well.
2. The `min` is set to 2, and the entire region from ~0% to ~20% of the slider is always 2, despite the fact that it should be increasing over that interval.

### After stopping dragging:
1. The reported value (both on the thumb and via onChange) jumps to the expected number. If the thumb is dropped at the rightmost point, onChange suddenly reports `10` and upon clicking the thumb again (without dragging), the thumb shows `10`.
2. In the region between 0% and ~20%, dropping the thumb generates accurate values.

**Comment by mlaursen** [comment]
Oh. I missed the sliding part of this. I'll reopen

**Comment by mlaursen** [comment]
Looks like the second problem was with my `calculateValueDistance` function. I wasn't offsetting the value while dragging with the `min` value (only on drag end or click)
