### ISSUE TITLE
[TextField] - Weird tab focus behavior

### ISSUE THREAD

**Issue by MichalWadowski** [mlaursen/react-md#408]
There is problem with setting up a focus in text controlls (TextField). When we click on the controll and then push TAB button, then we should be directed to the next element. Unfortunately, we are directed to an arbitrary element of the interface.

The example: https://codepen.io/MichalWadowski/pen/XgmrOy

When we click on the second text field and then push TAB button, then we are directed to the button instead of the third text field. When we push any other controll (e.g. button or checkbox), then the focus is set up correctly.

The problem occurs in Firefox 53, I think that in Chrome it works correctly. Additionally, I think that in the previous library versions these problems didn’t occur.

**Comment by mlaursen** [comment]
When I updated the css link to be:

```
https://unpkg.com/react-md@1.0/dist/react-md.light_blue-pink.min.css
```

instead of
```
https://unpkg.com/react-md/dist/react-md.light_blue-pink.min.css
```
it appears to work correctly in Firefox. It might be because of me accidentally publishing a 1.1.0-alpha to latest instead of next. I'll do some more debugging locally to see if It is a problem

**Comment by stickfigure** [comment]
Ah hah! This fixes my problem with SelectFields displaying very poorly (they look corrupted, missing most of the menu style). I've pinned the stylesheet in my app, but I would say this is a critical problem that will have subtle bad effects for pretty much every app built with react-md 1.0 :-(

**Comment by mlaursen** [comment]
Ahh. That's probably my bad in my documentation; I only have a very small and non-descriptive note about specifying the versions on my installation page.

I definitely recommend always specifying `https://unpkg.com/react-md@VERSION` when precompiled css or the UMD build since I'll be trying to keep everything backwards compatible, but when a major version change happens, all apps might break (major will be no backwards compatibility or just huge underlying changes).
