### ISSUE TITLE
[TimePicker] - Selected value of the TimePicker is "forgotten" by the clock

### ISSUE THREAD

**Issue by mattili** [mlaursen/react-md#438]
### Description
A previously  selected time is forgotten in the clock part of the TimePicker if it is closed by any other means than the "OK" button.
1. Open the TimePicker and set a value
2. Close the TimePicker with the "OK" button
3. Open the TimePicker again and close it by for example clicking the "Cancel" button
4. Open the TimePicker again -> Initial value of the clock is once again the first value the component was rendered with, not the value chosen when "OK" was clicked (the value in the text field)

### Link to a gist or code sample where the issue can be reproduced

Follow the steps above to reproduce the issue in the sample:
https://codepen.io/mattili/pen/eRbYmW
### Version
- React 15.6.1
- React-MD 1.0.16

**Comment by mlaursen** [comment]
I am going to update the logic a bit for this one. The clock will remember the last time as long as the text field has no value. If the text field has a value, it will use that instead.

So this means:
- User opens the TimePicker
- User selects some new time
- User closes the time picker by clicking the overlay or the cancel button
- User opens the TimePicker again

The TimePicker will remember their last selected time and display that.

- TimePicker has a value set (either by `value` prop or since they have already selected a value in the picker)
- User opens TimePicker
- The current value is displayed as the selected time
- User selects another time but closes the time picker by any action other than hitting the "Ok" button
- User opens the time picker again
- The user's last selected time is not selected. It will display the current value of the select field
