### ISSUE TITLE
ListItem props not being passed to the li node

### ISSUE THREAD

**Issue by amadois** [mlaursen/react-md#439]
### Description
Props passed ti the ListItem component are not passed to the root li element but to the AccessibleFakeInkedButton. This makes it impossible to fully customize the rendered list item.

I'd consider adding a fakeInkedButtonProps property and a listItemTextProps property to customize these two subcomponents and passing the remaining props ({ ...props }) to the li node.

### Version
- React: ^15.5.4
- React-MD: ^1.0.15

**Comment by mlaursen** [comment]
When I upgrade to the next major release (who knows when?) I am planning on making the remaining props apply to the `<li>` instead of the `AccessibleFakeButton`. Until then, I'll introduce the props: `itemProps`, `tileProps`, and a temporary migration helper prop `passPropsToItem`.

By default, the remaining props and the `tileProps` will be provided to the `AccessibleFakeButton` while the `itemProps` will be provided to the `<li>`. When the `passPropsToItem` prop is enabled, the remaining props will be passed to the `<li>` node instead.
