### ISSUE TITLE
[Switch] - controlled value regression in 1.0.16

### ISSUE THREAD

**Issue by chase** [mlaursen/react-md#454]
### Description
After npm install bumped to 1.0.16, some of my client's switch interfaces broke. These are controlled switches with `!`-ed values that worked in 1.0.15.
Now, in 1.0.16, the switches simply do not fire `onChange` events.

### Link to a gist or code sample where the issue can be reproduced
Using 1.0.16 (doesn't work): https://codepen.io/anon/pen/BZeQwp
Using 1.0.15 (works): https://codepen.io/anon/pen/rwgWvQ
### Version
- React - 15.6.1
- React-MD - 1.0.16

**Comment by mlaursen** [comment]
This isn't working because the `id` prop is required for switches to work (there is even a PropType warning about it). With the change in 1.0.15, the switch's track/ball was moved inside of the label so the correct `onClick` event would be triggered. Without an id, clicking/selecting/touching the ball does not trigger the hidden `input` change event.

https://codepen.io/mlaursen03/pen/OgeMLo (forked and just added the id prop)

**Comment by chase** [comment]
Thank you! I tend to ignore PropType warnings in really large codebases with legacy code, so I suppose that's on me. I'll be sure to pay attention in the future, even if it is just for accessibility features.
