### ISSUE TITLE
[Navigation Drawer] "drawerChildren" prop cannot scroll through the component when sidebar is full

### ISSUE THREAD

**Issue by ghost** [mlaursen/react-md#455]
### Description
If you give drawerChildren prop and the navigation is populated, the drawer cannot scroll to the items in drawerChildren.

### Version
- React - 15.3.0
- React-MD -1.0.16
- Browser

**Comment by mlaursen** [comment]
Yeah, this is because of how I handled scroll behavior. Right now the `navItems` `List` gets updated with a new className `md-list--drawer` that sets the `max-height: calc(100% - $current-toolbar-height)` so that it is scrollable.. I should probably update it so that there is just an additional container that handles the scroll instead.

Sadly I can't set the drawer to be scrollable since it breaks the fixed headers for some reason. Might be able to debug it more though.

**Comment by CalvinChhour** [comment]
Currently running into this, @yairodesu any tips on how you worked around the bug?
