### ISSUE TITLE
[ExpansionList/Panel] - Panel label overflows on phone screen sizes

### ISSUE THREAD

**Issue by crazyhatfish** [mlaursen/react-md#479]
### Description
When a large label is used on a screen < 358px, the label overflows the header.

I've spent a little time looking at `ExpansionPanel` and I think I get what its doing. Although I think the `overflown` prop would be put to better use on the header label rather than on the content, since it is fixed size. Although the `overflown` variable doesn't seem to change ever - but I'm probably wrong, I haven't tested this thoroughly.

### Link to a gist or code sample where the issue can be reproduced
https://codepen.io/anon/pen/RZgmxp (resize screen width to < 358px - most other components handle this screen resolution perfectly)

### Version
- React - v15.6.1
- React-MD - 1.0.18
- Browser - Tried on Firefox and Chrome

P.S great library btw :+1:

**Comment by mlaursen** [comment]
I believe I fixed this in 1.1.0 (only in alpha though) since I ran into this as well. I updated some of the logic so that it would automatically truncate for smaller devices. Check out the [Complex Example](https://react-md.next.mlaursen.com/components/expansion-panels#complex-example) on a mobile device. I can see about bringing this back to 1.0.19, but I'm not entirely sure if I can
