### ISSUE TITLE
[NavigationDrawer] - drawer shows when defaultVisible set to false

### ISSUE THREAD

**Issue by mkimberlin** [mlaursen/react-md#480]
### Description
The NavigationDrawer does not appear to be respecting the defaultVisible property.

```jsx
<NavigationDrawer
  navItems={[]}
  contentClassName="md-grid"
  drawerHeaderChildren={[]}
  drawerType={NavigationDrawer.DrawerTypes.TEMPORARY}
  defaultVisible={false}
  toolbarTitle="Nav Drawer Bug"
  toolbarChildren={[]}
  contentId="main-content"
>
```
or
```jsx
<NavigationDrawer
  navItems={[]}
  contentClassName="md-grid"
  drawerHeaderChildren={[]}
  drawerType={NavigationDrawer.DrawerTypes.PERSISTENT}
  defaultVisible={false}
  toolbarTitle="Nav Drawer Bug"
  toolbarChildren={[]}
  contentId="main-content"
>
```

### Link to a gist or code sample where the issue can be reproduced

You can find a codepen showing this behavior [here](https://codepen.io/mkimberlin/pen/jLLOOJ).

### Version
- React - Tested with 5.14.2 and 16.0.0-beta.2
- React-MD - Tested with 1.0.17 and 1.0.18
- Browser - Tested on Chrome

**Comment by mlaursen** [comment]
The `TEMPORARY` one can be resolved by using the new prop that was introduced (`constantDrawerType`). The persistent one is a bit more difficult since it is "invalid" to use a persistent type on mobile devices. If you also provide the `desktopDrawerType={NavigationDrawer.DrawerTypes.PERSISTENT}` this problem doesn't occur.

What is really happening behind the scenes is that it is respecting the `defaultVisible` prop, but once it mounts it calculates that it is a `FULL-HEIGHT` drawer since it matches the desktop media and the `desktopDrawerType` hasn't been updated and must be visible. I think this is fine as is with the available props.

**Comment by mkimberlin** [comment]
Thanks for the direction, @mlaursen.  I think that there is still a bit of an issue here, or maybe I'm misunderstanding the situation.  If no drawerType, mobileDrawerType or desktopDrawerType are defined then then shouldn't it behave the same way as if mobileDrawerType=TEMPORARY and desktopDrawerType=PERSISTENT?  Because, what I am seeing is that it completely respects defaultVisible=true if I set mobile and desktop drawer types to those defaults...but if I don't set them at all, or just set drawerType, then it ignores defaultVisible.

**Comment by mkimberlin** [comment]
I will throw together another couple of codepens in a little while...headed into a meeting in just a sec.

**Comment by mlaursen** [comment]
You're probably right. It feels like a lot of additional logic to add to the component which is why I am a bit hesitant to add it when an existing prop can be used to solve the issue. I'm also nervous about bugs that might appear if the user sets the `drawerType` to `PERSISTENT` but don't update it after it turns to mobile and everything displays incorrectly.

- Example of your pen with using `constantDrawerType` for temporary - [codepen](https://codepen.io/mlaursen03/pen/dzewdY)
- Example of your pen using `desktopDrawerType` for persistent - [codepen](https://codepen.io/mlaursen03/pen/RZyEMG)

I'll reopen this and think about adding the logic into my component, I _personally_ don't think it is a high priority though :/

**Comment by mkimberlin** [comment]
Yeah, I agree.  It's not high priority.  I can totally get around it.

BTW, I want to say thank you for this library.  It's easily the most complete and configurable MD component library that I've come across.  I've been extremely happy using it and I really appreciate all the work you've clearly put into it.  Further, the couple of times that I've run across an issue, you've been more responsive than I ever would have expected for someone working on this on their own.  My hat is off to you...great work.

**Comment by mlaursen** [comment]
Thank you! I am really glad you are enjoying it and it's always great having some positive feedback about the experience to keep me motivated to work on it :). I've mostly been trying to be responsive, give feed back, and document well since it was what was missing for the other libraries (for me).

So thanks again for the feedback!
