### ISSUE TITLE
[TextField] - Support additional input types

### ISSUE THREAD

**Issue by jackielii** [mlaursen/react-md#486]
### Description
TextField should not give errors when type is `datetime` and `datetime-local` 
### Images/Screenshots
![image](https://user-images.githubusercontent.com/360983/29420728-ba624f08-836a-11e7-9cf6-97cdd7a5b113.png)

### Version
- React -
- React-MD -
- Browser

**Comment by mlaursen** [comment]
This is mostly because I don't actually support
- color
- date
- datetime-local
- image
- month
- range
- time
- week

as they were not a part of the material design spec (or the `TimePicker`/`DatePicker`/`Slider`/`FileInput` should be used instead)

I can always update the PropTypes to include these, but I don't really want to have to support bugfixes for any display bugs (or the fact they need to be polyfilled for some browsers) that might happen for them. You _can_ always ignore the prop type warnings since they will be removed in production anyways.

I'll think about it a bit more.

**Comment by jackielii** [comment]
Thanks, that make sense
