### ISSUE TITLE
[TablePagination] - Displays incorrectly when large numbers are used

### ISSUE THREAD

**Issue by benhunt29** [mlaursen/react-md#489]
While paginating through a large table, as the current displayed rows increases its order of magnitude (10 to 100, 100 to 1000, etc), the pagination controls can sometimes go off of the table depending on the screen size. Perhaps there could be a maximum right position?

**Comment by mlaursen** [comment]
In 1.1.x, I have some styling in place to truncate labels and hide things so it can display better on smaller devices. I'll try it out on some bigger datasets to see if it still displays correctly.

[Demo](https://react-md.next.mlaursen.com/components/data-tables#simple-pagination)

**Comment by mlaursen** [comment]
I'm hoping for Sept 2, but I am going back on vacation next week so I'm not sure if I'll be able to get everything in... I'm running into a few outstanding bugs for Tabs and Menus in fixed elements. :/ I know how to do some of the work for the Menus, but the tabs will take a bit since I don't use them much (personally).

**Comment by benhunt29** [comment]
@mlaursen no problem, sounds good!
