### ISSUE TITLE
[SelectionControlGroup] - Add documentation/example to handle controlled checkbox components

### ISSUE THREAD

**Issue by Ardhimas** [mlaursen/react-md#494]
I noticed that the documentation/examples has a SelectionControlGroup component being used in the example for controlled Radio inputs. However, the Checkbox input section simply uses the Checkbox component in its controlled examples. Initially this led me to falsely believe that the SelectionControlGroup component is only usable in uncontrolled inputs and controlled Radio inputs, but upon digging into the source code I realized that it is possible.

It would be very helpful to future users for there to be a corresponding SelectionControlGroup example for controlled Checkbox inputs. I figured it out, but I can see a more junior developer being really confused.

I'm willing to make a PR if you want @mlaursen .

For reference:

- [Checkbox page](https://react-md.mlaursen.com/components/selection-controls/checkboxes)

- [Radio page](https://react-md.mlaursen.com/components/selection-controls/radios)

**Comment by mlaursen** [comment]
Oooh. I hadn't thought about that. I would welcome a PR that adds more examples.

Adding it to my 1.1.x branch might be easiest since it has [a better README](https://github.com/mlaursen/react-md/tree/release/1.1.x/docs#contributing) about how to contribute and the server was simplified, but you can choose 1.0.x if the examples should be added sooner.

**Comment by Ardhimas** [comment]
I love this project so I'll make the PR, but give me a week to get to it. Thanks again for all your hard work @mlaursen .
