### ISSUE TITLE
[NavigationDrawer|ListItem] activeClassName not passed to Component

### ISSUE THREAD

**Issue by hisapy** [mlaursen/react-md#503]
### Description

When creating a navItems with objects like 

```javascript
   {
      component: Link,
      activeStyle: {background: 'red'},
      activeClassName: 'some-class-name',
      leftIcon: icon && <FontIcon>{icon}</FontIcon>,
      to: path,
      primaryText: text
   }
```

The `activeClassName` prop is not passed to the Link component. However, `activeStyle` is passed to Link. The culprit appears to be in `ListItem` assigning `{...props}` to the `AccessibleFakeButtonInked`; the resulting object does not contain the `activeClassName` prop because it is filtered out before the spreading. 

To avoid this naming conflicts, a solution might be to use a `componentProps` key in the object to explicitly define which props should be added to the component to be rendered by the ListItem. i.e.:

```javascript
   {
      component: Link,
      componentProps: {
        activeStyle: {background: 'red'},
        activeClassName: 'some-class-name'
      },
      leftIcon: icon && <FontIcon>{icon}</FontIcon>,
      to: path,
      primaryText: text
   }
```
### Version
- React **15.6.1**
- React-MD **1.0.17**
- Browser: Chrome and Safari

**Comment by mlaursen** [comment]
This should be implemented already for 1.0.17. See #439 

For some more information about this... The reason the `activeClassName` is not passed to the `component` is that the `ListItem` itself uses `active` and `activeClassName`. So with the current implementation, you would use `tileProps` instead of `componentProps`. I do like `componentProps` as a name better though...
