### ISSUE TITLE
[EditDialogColumn] - Doesn't work on mobile

### ISSUE THREAD

**Issue by RudiUrbanek** [mlaursen/react-md#519]
In your documentation https://react-md.mlaursen.com/components/data-tables
if you try to use the editable inputs with a mobile device or tabblet. Whenever the keyboard appears the input overlay disappears making it impossible to use them.

**Comment by mlaursen** [comment]
So this is something I've been struggling to "fix" for awhile now.  This falls into the same bug that is described in the [Autocomplete with "Smart" Menus](https://react-md.mlaursen.com/components/autocompletes#using-smart-menus) example. It is basically *very* hard to fix because of how iOS and Android determine viewport height and the fact that Android triggers a resize event while iOS does not. It is actually the resize event on Android that causes it to immediately close.

There are a bunch of different hacks I could try to get it to work wonderfully across all mobile devices, but it would be a huge effort and large edit dialogs would still pose a huge issue.

This isn't the best solution right now, but if you want to use the `EditDialogColumn`, I would suggest using the `inline` view on mobile devices or going for a row editor view.
