### ISSUE TITLE
[Autocomplete] Props warning, onAutocomplete not working, anchoring

### ISSUE THREAD

**Issue by ostrebler** [mlaursen/react-md#552]
Hello mlaursen, thank you for the amazing free stuff you put out there.

I noticed three unexpected behaviours on the Autocomplete component. The first one is that it triggers the React unknown props warning when I pass an array of objects as "data" prop and when I type something in for the first time. Example : 

```
let data = [
    {_id: 'u1', name: 'Bob', otherData: 'stuff'},
    {_id: 'u2', name: 'Kevin', otherData: 'restuff'}
];

<Autocomplete id='test'
    data={ data }
    dataLabel='name'
/>
```

This triggers the following warning on first key hit :
```
Warning: Unknown props `_id`, `otherData` on <div> tag. Remove these props from the element. For details, see https://fb.me/react-unknown-prop
  in div (created by AccessibleFakeButton)
  in AccessibleFakeButton (created by withInk(AccessibleFakeButton))
  in withInk(AccessibleFakeButton) (created by ListItem)
  ...
```

The second issue is with the onAutocomplete callback. Your doc says that the onAutocomplete first argument will be the suggestion itself, but this : 
```
let data = [{...}, {...}];

<Autocomplete id='test'
    data={ data }
    dataLabel='name'
    onAutocomplete={ suggestion => console.log(suggestion) }
/>
```
will log 'undefined'. With the autocompleteWithLabel prop set to true, it just sends the 'name' field and not the whole object. My current turnaround is to use the suggestionIndex parameter, then `data[suggestionIndex]` to get the object.

The third thing is that It seems impossible to anchor the suggestion list above the text field. I set the anchor prop to `{ x: Autocomplete.HorizontalAnchors.CENTER, y: Autocomplete.VerticalAnchors.TOP }`, but it just stays at the bottom. I have exactly the same issue on SelectFields. Both use Layover, maybe it comes from there ?

Please let me know if I'm missing something here, or good luck for your fixings.

Olivier

**Comment by mlaursen** [comment]
Check out this codepen: https://codepen.io/mlaursen03/pen/NajExd?editors=0110

So to give some more explanations here are the changes and the reason why I did them.

#### Prop Type warning
The way to get rid of this is to use the [deleteKeys](https://react-md.mlaursen.com/components/autocompletes?tab=1#autocomplete-proptypes-delete-keys) prop. The `Autocomplete` will pass the entire `data` object into the `ListItem` component so you can add any additional functionality to each `ListItem`. Since all my components always forward all undocumented props down to the element, you will get this warning. The `deleteKeys` will remove the specified keys from the object before passing it to the `ListItem`

#### onAutocomplete Callback
By default the `onAutocomplete` provides the `data[dataValue]` so that's why you get `undefined` since the default `dataValue` (`value`) key does not exist in your object. Switching to `autocompleteWithLabel` will then provide the string as expected. There is an issue #425 about returning the whole object as the first param.

#### anchoring
This is probably something I need to document a bit more, but this isn't working as expected for multiple reasons. To have full backwards-compatibility I ended up making it so that if the `position` prop is set to `BELOW`, it overrides the anchor positions. I probably should update it to only do that if `simplifiedMenu` is still false though. Also, the `anchor` prop will not be used if the `simplifiedMenu` is `false` (defaulted to `false`).

Hopefully this was somewhat helpful. I'll try and add some more documentation

**Comment by ostrebler** [comment]
Thank you for that helpful answer. I was able to fix the first two issues.

For the anchoring, I don't get it. I tried several things and I'm not able to put the suggestion list above the text field. Here's is what I tried : 
```
<Autocomplete
    id={ 'autocomplete-member-' + key }
    anchor={{ x: SelectField.HorizontalAnchors.LEFT, y: SelectField.VerticalAnchors.TOP }}
    position={ Autocomplete.Positions.BOTTOM_LEFT }
    simplifiedMenu={ true }
/>
```

I tried with different HorizontalAnchors and positions, I doesn't seem to do the trick. Any advice ?

**Comment by ostrebler** [comment]
https://codepen.io/mlaursen03/pen/NajExd?editors=0110

Type for example the letter 'n' a try to navigate through the suggestions with key pad.

**Comment by mlaursen** [comment]
That part is a bug with the Layover. It doesn't know how to correctly position in elements that have a `transform` style applied to them. The dialog has `transform: translate3d(-50%, -50%, 0); left: 50%; top: 50%;` to center it in the page. I've been meeting to update the calculations for that, but I'm not too sure where to start yet.

**Comment by mlaursen** [comment]
I'm going to close this one and reference the ticket about the positioning. #580
