### ISSUE TITLE
[Tabs] - Slow scrolling on tabs.

### ISSUE THREAD

**Issue by daturon** [mlaursen/react-md#577]
When scrolling content in the tabs, the scrolling proceeds slowly, without smoothing/slipping.

iPhone 6S Chrome, Safari
React-md 1.1.6

**Comment by mlaursen** [comment]
This one is a bit hard to fix because the smooth scrolling is opt-in for iOS. Most of the problems occurs from using a full page `Dialog` in the examples. I can update the full page dialogs to use the `md-ios-scroll-momentum` mixin, but if there are any fixed toolbars on the page, they render slowly and badly when the user scrolls. You can "fix" this by manually setting the height of the scrollable content and using the mixin above, but it is a bit too hard to include in this library at the moment since there are a lot of different setups and positioning of elements.
