### ISSUE TITLE
[Grid] style prop doesn't apply

### ISSUE THREAD

**Issue by ostrebler** [mlaursen/react-md#596]
Hey there

### Description
When applying a style prop to the new Grid component, it doesn't apply. Using : 
```
static gridStyle = { position: 'sticky', top: '50px' };
// .......
<Grid style={ Homepage.gridStyle }>
   // ......
</Grid>
```

renders to : 
```
<div class='md-grid'>
   .....
</div>
```

Also, switching from React-MD 1.1.7 to latest (1.2.3) increased my dev bundle size from 7.68 MB up to 11.4 MB. Why is this ?
Thank you.

### Version
- React - 16
- React-MD - 1.2.3

**Comment by mlaursen** [comment]
It looks like I forgot to provide the `style` prop to the `Grid` when the children is not a callback function. Should be an easy fix.

I'll need to know more about your build environment and how you are importing react-md components to help with the bundle size issue.

**Comment by ostrebler** [comment]
I import them like `import TextField from 'react-md/lib/TextFields'`
For the Grid system, I just copied the doc with `import { Grid, Cell } from 'react-md'`. Does that import the whole library ?

Here is my webpack config : 
```
var debug = process.env.NODE_ENV !== "production";
var webpack = require('webpack');
var path = require('path');

module.exports = {
  devtool: debug ? "inline-sourcemap" : false,
  entry: "./client/js/Finder.js",
  module: {
    loaders: [
      {
        test: /\.jsx?$/,
        exclude: /(node_modules|bower_components)/,
        loader: 'babel-loader',
        query: {
          presets: ['react', 'env', 'stage-0'],
          plugins: ['react-html-attrs', 'transform-class-properties', 'transform-decorators-legacy'],
        }
      }
    ]
  },
  output: {
    path: __dirname + "/client/",
    filename: "finder.min.js"
  },
  plugins: debug ? [] : [
    new webpack.DefinePlugin({ 'process.env': { NODE_ENV: JSON.stringify('production') }}),
    new webpack.optimize.ModuleConcatenationPlugin(),
    new webpack.optimize.UglifyJsPlugin()
  ],
};
```

**Comment by mlaursen** [comment]
Ahh yeah, sorry. The huge jump in size is the fact that you are now importing two versions of the react-md library: rollup and just pure babel transforms. I actually **did not** fully implement module support since it looks like creating an es module bundle with rollup did not work as expected: #587

To reduce it back to your normal size, you'd still have to do 
```
import Grid from 'react-md/lib/Grids/Grid';
import Cell from 'react-md/lib/Grids/Cell';
```

Or change **all** of your imports to be `import { Component } from 'react-md'`. It still imports the entire library, but it'll actually be smaller on large scale applications with a lot of code-splitting since the rollup bundle is a lot more optimized than the pure babel transforms in the `react-md/lib` namespace.

I hope this made sense...

**Comment by ostrebler** [comment]
Very clear answer, thank you.
