### ISSUE TITLE
[Menus] - Cascading dropdown has wrong relative parent when in DialogContainer

### ISSUE THREAD

**Issue by Skysplit** [mlaursen/react-md#599]
### Description
Nested items in `Menu` with `cascading` prop that is inside `DialogContainer` component have position calculated in relation to wrong parent (closest relative parent is `DialogContainer`[because of `translate3d`], but its calculated relatively to `window`)

### Link to a gist or code sample where the issue can be reproduced
https://codepen.io/anon/pen/qPGGeQ

### Version
- React - 15
- React-MD - 1.2.3

**Comment by mlaursen** [comment]
I think an easier solution might be to change the `DialogContainer` to no longer position the `Dialog` in the center using:
```scss
left: 50%;
top: 50%;
transform: translate3d(-50%, -50%, 0);
```

since I am having to do additional checks and fixes for this weird translation. It would be easier to center by just using:

```
align-items: center;
display: flex;
justify-content: center;
```

This just means that any custom positioning of the `Dialog` would have to be changed to using `margin` instead of `left` or `top`.

I'll think about it some more.

**Comment by Skysplit** [comment]
I'm nowhere near to be good at CSS, but using flexbox sounds really good :D

**Comment by mlaursen** [comment]
This has now been added as a new opt-in feature until the next major release where it will be enabled by default.

Setting `$md-dialog-use-flex-positioning: true` will now use flex-based centered instead of the old `left`/`top` + `translate3d` hack.
