### ISSUE TITLE
[EditDialogColumn] - visibleOnFocus prop behaviour inconsistent at best

### ISSUE THREAD

**Issue by alt-jero** [mlaursen/react-md#608]
### Description
In DataTable example docs the EditDialogColumn components marked as "no focus open" are the only ones aside from the inline component which *do* open with focus.

The behavior of the component in the codepen template is less consistent, but seems to hover around the opposite behaviour (visibleOnFocus=true -> no focus open) however it also (as when first loading the page after a refresh) sometimes affords all the possibilities of the visibleOnFocus attribute focus when they are first opened.

Actually I can't make heads or tails of when it decides to work proppositely (properly but opposite) and when it decides to just give everything autofocus. I thought it had to do with the page (read: the whole codepen thing) being refreshed vs simply editing the pen and having the view refreshed that way, but apparently not.
### Link to a gist or code sample where the issue can be reproduced
https://codepen.io/anon/pen/PONxNN?editors=0011

### Version
- React -
- React-MD -
- Browser Safari 11.0.1 (unknown if browser specific)

**Comment by mlaursen** [comment]
This is probably a documentation problem on my end since the `visibleOnFocus` prop is really only for keyboard focus behavior. When the user tab-focuses the column, it will either automatically open up the text dialog or just show the focus outline requiring the user to press enter or space to open the dialog.

It appears that all browsers are following the expected behavior to me from both the codepen and the documentation website example.
