### ISSUE TITLE
[BottomNavigation] - Can you have more than 3 items without the shifting effect?

### ISSUE THREAD

**Issue by petr166** [mlaursen/react-md#637]
### Description
In the current [documentation](https://react-md.mlaursen.com/components/bottom-navigations), it says "A fixed bottom navigation will be used when there are exactly 3 links. A shifting bottom navigation will be used when there are more than 3 links".   
I want to have a 4 (maybe 5) item `BottomNavigation`, but disable the shifting effect(show the label on the active item). I couldn't find a way to do this in the documentation, so I am wondering if it is possible via props. If not, I suggest it to be implemented, as it would be nice to have the option.

### Version
- React - v15.4.2
- React-MD - v1.2.8

**Comment by mlaursen** [comment]
Right now it isn't possible mostly because of mobile real estate. It changes to a "shifting" bottom navigation because there isn't enough real estate on most mobile devices to show more than 3 labels at once. It would be nice to add this feature for devices that have the real estate though.

**Comment by idlecat** [comment]
First of all, thanks for the great library! 
I feel the shifting effect quite unpleasant. Plus, a lot of apps, including "Google Photos", "Google Newsstand", Quora, Pintest, have 4 or 5 bottom links and they are all fixed. Real eastate shouldn't be an issue for 5 links. Anyway, it's better to give user a choice instead of magically switching to shifting mode for >3 links.

Regards,

**Comment by mlaursen** [comment]
I've been rewriting the components in react-md with Typescript and using the new context API, so when I get to the Bottom Navigation component again I'll make try a few different scenarios to add this feature. It definitely is a nice feature to have
