### ISSUE TITLE
[Styling] - How are styles applied to react-md components?

### ISSUE THREAD

**Issue by sfeldkamp** [mlaursen/react-md#639]
https://react-md.herokuapp.com/

I am seeking clarification about how scss is applied to react components (and ultimately the DOM elements).  I think webpack builds it into a global scss file.  So selector specificity is still an important consideration.

I could add CSS Modules which as far as I can tell is just a way of creating high specificity of global rules through dynamic class names.

Alternately, I could use Shadow DOM to avoid global styles, but it isn't supported fully by browser's yet.  There is a polyfill, but it appears to be challenging to add that to webpack.

Is that all correct?

**Comment by mlaursen** [comment]
Right now the main process is:

compile scss to css -> create stylesheet -> apply class names to elements

All of the styles within react-md will be prefixed with `md-` and the class names are following BEM (somewhat) so that should hopefully fix some of the global namespace issues.

It could be that you can use CSS Modules (or any of the other frameworks/naming conventions out there) for custom styles applied on top of react-md to help even more with namespace issues.



And sorry about heroku being down! I am not on the paid tier so it stops working after 550 hours for the month. You should really only need to go to the heroku url if you are not a memeber of the Slack channel yet, otherwise you can just go to https://react-md.slack.com

**Comment by pietrofxq** [comment]
Is there a easy way to use css modules with this library? I would like to use it, but I have a full setup with css modules + postscss and wouldn't want to introduce SASS to the project.
