### ISSUE TITLE
[TextField] - Warning: Received `true` for a non-boolean attribute `error`

### ISSUE THREAD

**Issue by asartalo** [mlaursen/react-md#699]
### Description
When a TextField has a leftIcon or rightIcon which is a `<Button />` and an error is set, a warning appears that says: Warning: Received `true` for a non-boolean attribute `error`. A workaround is to set the attribute `leftIconStateful={false}` or `rightIconStateful={false}` depending on the icon.

### Images/Screenshots
![image](https://user-images.githubusercontent.com/310708/36942062-3cad196c-1fa5-11e8-9769-c0f983967bb6.png)

### Link to a gist or code sample where the issue can be reproduced
https://codepen.io/asartalo/pen/xYemgr?editors=0010

### Version
- React - 16.2.0
- React-MD - 1.2.11
- Browser: Possibly Any but tested on Firefox and Chrome

**Comment by mlaursen** [comment]
This is actually because of how [the icons are created](https://github.com/mlaursen/react-md/blob/master/src/js/TextFields/TextField.js#L502-L521) and gain "state". It works for `FontIcon` and `SVGIcon` because those were the intended use-cases but you can get around this error by just creating a wrapper that removes the icon specific props that are passed to the button.

```
const IconButton = ({ primary, error, className, ...props }) => (
  <Button
    {...props}
    icon
    primary={primary && !error}
    className={cn({ 'md-text--error': error }, className)}
  />
);
```

One of the biggest "features" in react-md is being able to pass any prop to any component and have it applied, but it does cause weird problems like this. I could also update Buttons so that they have the ability to be rendered with error states.

**Comment by asartalo** [comment]
I see. I think I'll use your approach then. Thanks for the response!
