### ISSUE TITLE
[Menu] - Cascading menus in safari doesn't appears

### ISSUE THREAD

**Issue by lepirlouit** [mlaursen/react-md#705]
### Description
Cascading menus doesn't appears in safari 
### Images/Screenshots
![image](https://user-images.githubusercontent.com/1354968/37514510-709d596e-2908-11e8-8f1d-a741fec1d9e8.png)

### Link to a gist or code sample where the issue can be reproduced
https://react-md.mlaursen.com/components/menus#google-docs-clone
### Version
- React - 16.2.0
- React-MD - 1.2.11
- Browser : Safari 11.0.3 (13604.5.6)

**Comment by mlaursen** [comment]
Yeah, this one is going to be decently hard to fix. This is due to Safari being one of the only browsers that does not render `position: fixed` or `position: absolute` that appear in a container that has overflow set. So this could be fixed by either updating menus to portal the cascading menus out or making it so that the overflow is set to visible on the parent list when a cascading menu is opened (this would also prevent scrolling on that parent list while a sub menu is open).

I think updating menus and lists to support portals would be the best fix since there are other issues (#613) that have this same bug.
