### ISSUE TITLE
[Autocomplete] - autoComplete="off" does not work in Chrome

### ISSUE THREAD

**Issue by alhaag** [mlaursen/react-md#709]
### Description

It is common knowledge that Chrome ignores the autocomplete property.

I've tried to make sure Chrome does not suggest values for the AutoComplete type field, but I only succeeded by inserting a dummy value into the property, such as autoComplete = "otrher_field", but this generates the following warning:

```
warning.js:33 Warning: Failed prop type: Invalid prop `autoComplete` of value `otrher_field` supplied to `Autocomplete`, expected one of ["on","off"].
```

My suggestion is to release any value to the autoComplete property or create a contour so that Chrome does not automatically populate this type of field.

### Version
- React : 16.2.0
- React-MD: 1.2.12
- Browser: Google Chrome 65.0.3325.181 64bits

**Comment by mlaursen** [comment]
I'm leaning towards supporting more autocomplete options, but I'll think about it a bit more.

**Comment by alhaag** [comment]
Is there any other outline option to prevent Chrome from autocomplete?

**Comment by ochtec** [comment]
Wanted to add to this one as well. I don't think we're necessarily looking for more autocomplete support, but a way around the fact that Chrome ignored autocomplete="off". So we can do autocomplete=`somerandomstring` and Chrome won't attempt to autocomplete, but we get a proptype error that the component only accepts ['on', 'off'], which is useless for chrome since off is ignored.

**Comment by mlaursen** [comment]
Makes sense. I'll update the prop-types for this one to just be `PropTypes.string` and update the documentation to point to valid options of `'on'`, '`off`' and link to the [disabling autocompletion](https://developer.mozilla.org/en-US/docs/Web/Security/Securing_your_site/Turning_off_form_autocompletion#Disabling_autocompletion) MDN docs
