### ISSUE TITLE
[SelectionControlGroup] onChange on radio SelectionControls via SelectionControlGroup doesn't trigger during tab navigation

### ISSUE THREAD

**Issue by nbolten** [mlaursen/react-md#719]
### Description
I tried passing onChange to individual selection controls (as a list of simple objects, per the docs). While clicking on a given radio button triggered onChange, tab navigation (tab to radio buttons, arrow keys to move, space to select) would never trigger the onChange.

For my use case, just putting the onChange on the entire SelectionControlGroup works fine. If this is the designated way to handle `type='radio'` SelectionControlGroups, it should be added to the docs as a warning.

I dived into the code a little, and everything seems to work up until `this._input.click()` gets called, which does not trigger onChange. I haven't gone any deeper to figure out what differentiates this from actually clicking the radio button.

### Link to a gist or code sample where the issue can be reproduced
https://codepen.io/anon/pen/ZxZpdw

### Version
- React - 16.2.0
- React-MD - 1.2.13

**Comment by mlaursen** [comment]
The [Radio Example](https://react-md.mlaursen.com/components/selection-controls#radio-example) talks about this, but maybe I didn't put enough information there. With the rewrite work I am doing, I am going to see if I can make the radio component not rely on the SelectionControlGroup (it only needs it right now because of how I am rendering the icons)
