### ISSUE TITLE
[DialogContainer] All nested dialogs close with ESCAPE key

### ISSUE THREAD

**Issue by ryanmurakami** [mlaursen/react-md#729]
### Description
When dealing with nested dialogs (eg. https://react-md.mlaursen.com/components/dialogs#nested-dialogs), the ESCAPE key closes all open dialogs instead of the most recent dialog. For instance, if a date picker is opened from a dialog, pressing ESCAPE closes both the date picker and the base dialog. It would be great if the ESCAPE key only closed the most recent dialog.
### Version
- React - any
- React-MD - current
- Browser - tested on Chrome & Firefox

**Comment by mlaursen** [comment]
This becomes really hard since dialogs can be created anywhere in the app at any time and the dialogs aren't guaranteed to be children of each other. This is a nice feature to add but will be difficult to make work out of the box. This can currently be fixed by adding some code yourself when the child dialogs appear, you set `closeOnEsc={false}` on all dialogs that are not "at the top".

So for the [Nested Dialogs example](https://react-md.mlaursen.com/components/dialogs#nested-dialogs), you would update the `MainDialog` to apply `closeOnEsc={false}` when the `InnerDialog` is visible.

I can keep this in mind for later though to see if it _could_ automatically be built-in.

**Comment by mlaursen** [comment]
This type of functionality is built-in to v2 now -- https://react-md.dev/packages/dialog/demos#nested-dialogs
