### ISSUE TITLE
[Theming] - Multiple themes at the same page

### ISSUE THREAD

**Issue by pinokkkio** [mlaursen/react-md#737]
What is the right way to use different themes within the same page at this library?

**Comment by mlaursen** [comment]
I think this really depends on your use case, so I'll link some of the related documentation, how I did it for the documentation site, and another small example.

The base information for additional theming is
- [Updating/Modifying Theme](https://react-md.mlaursen.com/customization/themes#updating-modifying-the-theme)
- [mixin react-md-theme-everything](https://react-md.mlaursen.com/customization/themes?tab=1#mixin-react-md-theme-everything)

In my documentation site, I make it so each user can have their own theme applied after viewing the [ThemeBuilder](https://react-md.mlaursen.com/customization/theme-builder), making a change, and having the "Save for future visits" checkbox checked. The way the theme builder works is to create an additional link tag with the current theme as a filename. So setting `primary-color: teal`, `seconary-color: pink`, `hue: 200` from that page would create a link like:
```
<link id="custom-theme-styles" rel="stylesheet" href="/themes/teal-pink-200.css">
```
which would then compile using [this route handler](https://github.com/mlaursen/react-md/blob/0d6522b21aaba2723d96edbfd2b8cb7c5c12bc50/docs/src/server/themes.js#L77) which will compile a new stylesheet with the provided theme variables. [Here is how it is compiled](https://github.com/mlaursen/react-md/blob/0d6522b21aaba2723d96edbfd2b8cb7c5c12bc50/docs/src/server/themes.js#L33-L65)

From there, I add a class to the html tag named "custom-theme" so that the custom theme will override all the defaults.

My use case is probably a bit easier than multiple themes on the same page, but you should be able to use the same idea with the `react-md-theme-everything` mixin's 4th argument for class names, so you could try doing something like:
```scss
@include react-md-theme-everything($md-teal-500, $md-pink-a-200, false, 'theme-1');
@include react-md-theme-everything($md-orange-500, $md-purple-a-400, false, 'theme-2');
// ... any others
```

```jsx
<div>
  <section className="theme-1">
    {... elements ...}
  </section>
  <section className="theme-2">
    {... elements ...}
  </section>
</div>
```

Everything in the `theme-1` section should have the a teal and pink theme while everything in the `theme-2` section will be orange/purple.

However, you might not need to theme every component, so it is useful to check out all the `react-md-theme-COMPONENT_NAME` mixins on the [Themes SassDoc page](https://react-md.mlaursen.com/customization/themes?tab=1#mixin-react-md-theme-autocompletes)

**Comment by pinokkkio** [comment]
So, if I want to overwrite some properties using custom class (my-card-text for component [Card](https://react-md.mlaursen.com/components/cards)) me need to write something like that:
```scss
.theme-1, .theme-2 {
	.my-card-text {
	     font-size: 10px;
	}
}
```

Is it only way?

**Comment by mlaursen** [comment]
It's the only way that I know of right now. You could also try using [css variables](https://developer.mozilla.org/en-US/docs/Web/CSS/Using_CSS_variables), but it'll basically be the same I think.
