### ISSUE TITLE
[ListItem] - When used in [NavigationDrawer] and minimized to show only icon, the expanderIcon is protruding and the sub links are flying

### ISSUE THREAD

**Issue by jairusd** [mlaursen/react-md#739]
### Description
As you can see in the screenshot, the issue is not very hard to miss. Maybe we can remove the indention in icons view and show something that tells the user that the icon has dropdowns? I'm not so sure how to portray this either.
### Images/Screenshots
![image](https://user-images.githubusercontent.com/36670564/40079867-cd9f05d0-58bb-11e8-9a73-d8e2723358ab.png)

### Version
- React - 16.3.2
- React-MD - 1.3.1
- Browser  - Not browser specific

**Comment by mlaursen** [comment]
This one is a bit tricky since I personally think it should be invalid to have nested routes when using a mini drawer, but it's annoying to have a rule like that. It is currently possible to render whatever you want in the mini drawer right now to fix this weirdness by using the [extractMini](https://react-md.mlaursen.com/components/navigation-drawers?tab=1#navigation-drawer-proptypes-extract-mini) and [miniDrawerChildren](https://react-md.mlaursen.com/components/navigation-drawers?tab=1#navigation-drawer-proptypes-mini-drawer-children) props.

Here is a [live example](https://codepen.io/mlaursen03/pen/vjzjEo?editors=0110) using these 2 props together to create a "nicer" mini drawer experience. Since this might not be what users want all the time, you'll probably want to update the custom rendering a bit.

**Comment by jairusd** [comment]
i came up with this solution with your recommendation:
![image](https://user-images.githubusercontent.com/36670564/40099492-d318fc6c-5912-11e8-9719-d712933427a3.png)
![image](https://user-images.githubusercontent.com/36670564/40099504-e3242bd6-5912-11e8-9ac6-250630f2fee4.png)
So what this does is create a single list of [ListItem] instead of creating subgroups
![image](https://user-images.githubusercontent.com/36670564/40099555-19995de4-5913-11e8-862f-6e40e5cada71.png)
Thanks for the fast reply man :)

**Comment by jairusd** [comment]
Thanks, I resolved the issue by instead of showing nested routes, i just flattened the list when minimized into icons, example:

home
about
  -- company
  -- myself

would be translated into:

home
company
myself
