### ISSUE TITLE
css class 'md-drawer-relative' is not in sync with Drawer default Behavior

### ISSUE THREAD

**Issue by tenorius** [mlaursen/react-md#750]
The class is not in sync with the drawer component behavior. When the drawer closes after resizing the window, the margin added by the class in the sibling component keeps applied. Why not make the media query on the class follow the same behavior of the drawer?

**Comment by mlaursen** [comment]
Right now, it is normally up to the developer to remove the `.md-drawer-relative` and `.md-toolbar-relative` class names as needed since the toolbars and drawers can appear anywhere on the page and might cause issues if some defaults were set. I think it's a good idea to add a built-in solution to automatically handle this though.
