### ISSUE TITLE
Change behaviour of FullWidth property in TextField

### ISSUE THREAD

**Issue by carlosforero** [mlaursen/react-md#76]
Currently FullWidth in Text Field is used to fit the input in a full width Form, but would be nice if it were possible to have a property for only to change the width to 100%, without change any other thing in the field. I know that it is possible using the style property, but it is not simple because is necessary to deal with different elements (input, container, right icon, ...), besides that, it would be nice to have FullWidth also in Select Field, and Select Field has more elements to deal.

So, I propose for the current behaviour to use the name Block (like bootstrap buttons) instead of FullWidth, and use FullWidth just for the width of Text Fields and Select Fields.

I've implemented these proposed changes: https://github.com/carlosforero/react-md/commit/cc7bb0ff52b535579c01c242261fe8d4bd96959c

Let me know any observation, in order to send a PR.

**Comment by mlaursen** [comment]
I think this is a good idea. I am a little iffy about the naming. I had gone with `fullWidth` before because it was how it was named in the Material Design docs. However, I do believe `block` is a better name describing how it looks and feels.

I think this will be a good change for `0.2.0`. I will add some deprecation warnings for `0.1.3` about the switch.

Looking at the commit, you will probably fail lint. Would you like comments on that commit, or once you have opened the pull request?

**Comment by carlosforero** [comment]
@mlaursen I've opened the PR https://github.com/mlaursen/react-md/pull/77.

The Travis Build failed, but I think the problem is not related to the new code.

**Comment by mlaursen** [comment]
https://travis-ci.org/mlaursen/react-md/builds/128899752#L349

Are you able to see the travis logs?  It looks like you are failing some rules for scss lint.

**Comment by carlosforero** [comment]
@mlaursen Fixed.

**Comment by mlaursen** [comment]
Ok, once I get some time, I'll roll out the `0.1.3` release to add deprecation warnings and then this ticket in `0.2.0`

**Comment by mlaursen** [comment]
Versions `0.1.3` and `0.2.0` have been published. Marking this as done.
