### ISSUE TITLE
[Textfield] - How do you get the value from a TextField?

### ISSUE THREAD

**Issue by fieldse** [mlaursen/react-md#792]
Hi. React noob here. 
I can't figure out how to get the value from a TextField component. (I've read the [docs](https://react-md.mlaursen.com/components/text-fields?tab=1#text-field-proptypes-value) on TextField value getter.)

The slack channel is also down, otherwise I'd ask there. A pointer in the right direction would be much appreciated.

My component hierarchy looks like this:

```
Dialog Modal
 - Button  onClick() -> this.show() (Makes modal visible)
 - DialogContainer
   \ - TextField   <-- (I want to get the value of this)
     - actions:  save() - get value of Textfield, send to callback function, hide the Dialog
  
```

When a user clicks Save button on the dialog, I want to get the value of the TextField.

TextField is defined in constructor():
```
  constructor(props) {
    super(props);
    this.inputField =  <TextField ... />
```
`this.inputField.value` returns undefined. What am I doing wrong?

**Comment by mlaursen** [comment]
Sorry about the Slack channel being down -- I'm running the auto-inviter on a Heroku instance that only gets 550 hours per-month. If you have already signed up, you can go directly to https://react-md.slack.com otherwise it should be back on the September 1st.

If you want to follow the docs, the way you can get the value from the text field is by using a [React ref](https://reactjs.org/docs/refs-and-the-dom.html). So you could update your Dialog component to look something like this:

```diff
 class Example extends React.Component {
   constructor(props) {
     super(props); 

+    this.inputField = React.createRef();
   }

   save = () => {
+    let value = '';
+    if (this.inputField.current) {
+     value = this.inputField.current.value;
+    }

     // ... do logic
   }

   render() {
     return (
       <DialogContainer {...props}>
         <TextField
           id="some-unique-id"
           label="Some label"
           placeholder="Type text here..."
+          ref={this.inputField}
          />
       </DialogContainer>
     );
   }
 }
```

However, depending on how complex your form might be, it might be better to store the value in state and use the `onChange` prop with `value` instead

```diff
 class Example extends React.Component {
   constructor(props) {
     super(props); 

-    this.inputField = React.createRef();
   }

   save = () => {
-   let value = '';
-   if (this.inputField.current) {
-    value = this.inputField.current.value;
-   }
+   const { value } = this.state;

     // ... do logic
   }

+  handleChange = (value) => {
+    this.setState({ value });
+  }

   render() {
     return (
       <DialogContainer {...props}>
         <TextField
           id="some-unique-id"
           label="Some label"
           placeholder="Type text here..."
-          ref={this.inputField}
+          value={this.state.value}
+          onChange={this.handleChange}
          />
       </DialogContainer>
     );
   }
 }
```

**Comment by fieldse** [comment]
Awesome! Thanks for the response Mikkel!
