### ISSUE TITLE
Feature request: custom renderDate function and date class provider for DatePicker

### ISSUE THREAD

**Issue by madc0der** [mlaursen/react-md#799]
Hello! Thank you for perfect UI framework!

Just want to be able to create static month calendar with highlighting for specified dates.
Static month calendar is possible with inline, visible, textFieldStyle/textFieldClassName props. But not highlighting of dates.

I suggest to add following props:

- renderDate(date, day) => node
- calendarDateClassNameProvider(date, day) => string
- onPreviousMonth(date)
- onNextMonth(date)
- onYearSelected(date)

In order to allow custom date rendering (i.e. <sub> hint about pending tasks) and to style specified dates. onPreviousMonth, onNextMonth, onYearSelected are helpful to load required data for new month.

Here are my changes: https://github.com/mlaursen/react-md/compare/master...madc0der:master
Its not PR because: not sure about naming, no tests and no changes in docs. Plz let me know if its suitable to be PR.

Example - highlight 9/18 and show one event for this date:
![image](https://user-images.githubusercontent.com/5368643/45602312-c4e91a00-ba24-11e8-904e-018a7a9cd569.png)

**Comment by mlaursen** [comment]
Hey, sorry for taking a bit to respond. I think this looks great! I would definitely accept a PR for this feature since it'll help make it more customizable.

I think I would like `dateRenderer` and `getDateClassName` instead of `renderDate` and `calendarDateClassNameProvider` just to be more in-sync with my naming paradigm in v2. The main documentation should auto-generate with the prop jsdoc you added, so otherwise it would just need to be updated to include the Typescript definition updates and ideally another example showcasing using the `dateRenderer` prop (can also use the other 3 new props as well if they tie in nicely).

Let me know if you run into any problems with the dev environment or running the documentation server locally and I'll try to help!

**Comment by madc0der** [comment]
Thank you! Will do!
