### ISSUE TITLE
[Dialog] - Allow closeOnEsc to be true when modal is true

### ISSUE THREAD

**Issue by jwillia** [mlaursen/react-md#803]
### Description
Make it possible to have a dialog with modal true and closeOnEsc true.  We need to have a dialog that closes on escape, but does not close when the user clicks on the overlay.  This could be achieved by honoring the closeOnEsc prop even when modal is true.
### Images/Screenshots
N/A
### Link to a gist or code sample where the issue can be reproduced
N/A

### Version
- React - Latest
- React-MD - Latest

**Comment by mlaursen** [comment]
Good call. I'll add this in today or tomorrow.

Do you think it would be better to just update the functionality so that if the `closeOnEsc` prop is enabled, the escape key will **always** close the dialog or modal OR introduce a new prop `closeModalOnEsc` which would be a workaround for modals. I'm leaning more towards the first one.

**Comment by jwillia** [comment]
I agree, the first sounds preferable.
