### ISSUE TITLE
onChange function on Checkbox is not getting called

### ISSUE THREAD

**Issue by nikhilgoswami** [mlaursen/react-md#835]
**Describe the bug**
Might be my silly mistake but onChange function is not getting called on Checkbox at all

**To Reproduce**
 Create a react app
 Copy this code in it 
 `<Checkbox
    id="someValue"
    name="someValue"
    label="Some Value"
    value="someValue"
    checked={this.state.someValue}
     onChange={(value, e) => this.handleCheckbox(value, e)}
  />`

**Expected behavior**
The handleCheckbox function should be called with two arguments.

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - chrome
 - latest

**Smartphone (please complete the following information):**
 Not applicable

**Additional context**
TextField onChange is working fine

**Comment by mlaursen** [comment]
Hmm, how about checking out this code sandbox: https://codesandbox.io/s/jolly-bell-qm12p

It seems to work for me, but it might just be updating your code to do `onChange={(checked, e) => this.handleCheckbox(checked, e)}` instead. Checkboxes provide the `checked` state instead of the `value` [as the first argument](https://react-md.mlaursen.com/components/selection-controls?tab=1#selection-control-proptypes-on-change).
