### ISSUE TITLE
[Collapse] - Animation is sometimes skipped when collapsing or expanding

### ISSUE THREAD

**Issue by markdon** [mlaursen/react-md#842]
**Describe the bug**
Animation is sometimes skipped when collapsing or expanding.
![COLLAPSE!!!!!!!!!!! EXPAND!!!!!!!!!!!!](https://i.imgur.com/aZ8yLVM.gif)

**To Reproduce**
1. Go to https://react-md.mlaursen.com/components/helpers/collapses
2. Click on 'Toggle Collapse' (or a collapse in the side bar) a few times.
3. Observe animations are sometimes skipped.

**Expected behavior**
Collapse and expand animations always play.

**Desktop (please complete the following information):**
Windows Desktop Chrome 75 

**Additional context**
react-md is great 😉

**Comment by mlaursen** [comment]
I think this is actually a problem with the `react-spring` library I'm using for that animation :/ This is fixed in the [v2 transition package](https://react-md.dev/packages/transition/demos#collapse-examples) since I stopped using that library to have a fixed transition duration, so I might hold off on fixing this until the eventual v2 release.
