### ISSUE TITLE
typescript: Cannot find module 'react-md'

### ISSUE THREAD

**Issue by lindomar-oliveira** [mlaursen/react-md#861]
I'm using **react-md v2 (2.0.0-alpha.11)**.

Erro _TS2307_: **Module not found: Can't resolve 'react-md' in ....**

My `tsconfig.json`

> {
  "compilerOptions": {
    "allowJs": true,
    "allowSyntheticDefaultImports": true,
    "esModuleInterop": true,
    "forceConsistentCasingInFileNames": true,
    "isolatedModules": true,
    "jsx": "react",
    "lib": [
      "dom",
      "dom.iterable",
      "esnext"
    ],
    "module": "esnext",
    "moduleResolution": "node",
    "noEmit": true,
    "noImplicitAny": true,
    "resolveJsonModule": true,
    "skipLibCheck": true,
    "strict": true,
    "target": "es6"
  },
  "exclude": ["build", "node_modules"],
  "include": ["src"]
}

**Comment by mlaursen** [comment]
Oof. When I fixed the build speeds and bundling all the default themes (9e03dcd), I accidentally removed the non-UMD build from the base `react-md` package.. Thanks for catching this!

I'm currently wrapping up the final table changes and hoping to release v2.0.0-alpha.12 Friday night or Saturday morning which should include a fix for this as well. Until then, you _should_ be able to install the scoped packages instead since those still generate the `types` directories.

I can release a v2.0.0-alpha.12 tonight if needed so the base `react-md` package can be used, but the updated table documentation/functionality won't be complete. Let me know if the quick partial patch is preferred.
