### ISSUE TITLE
SassError in set custom color for override theme default

### ISSUE THREAD

**Issue by lindomar-oliveira** [mlaursen/react-md#873]
I'm using **react-md v2 (2.0.0-beta.1)**.

When trying to define a custom primary color, the following error occurs:
```sh
SassError: Invalid material design color: '#3498db'. If this was intentional because your app does not use material design colors, set a fallback color instead to get a correct color for the provided swatch: 300.
        on line 66 of node_modules/@react-md/theme/dist/_functions.scss, in function `rmd-theme-get-swatch`
        from line 69 of node_modules/@react-md/chip/dist/_variables.scss
        from line 6 of node_modules/@react-md/chip/dist/_functions.scss
        from line 12 of node_modules/@react-md/chip/dist/_mixins.scss
        from line 7 of node_modules/react-md/dist/_react-md.scss
        ...
>>       @error $error-msg;

   -------------^
```

File: `index.scss`
```scss
@import "./variables";

@import "~react-md/dist/react-md";

@include react-md-utils;
```

File: `_variables.scss`;
```scss
@import "~@react-md/theme/dist/color-palette";

$rmd-theme-primary: #3498db;
$rmd-theme-secondary: #d35400;
````

**Comment by mlaursen** [comment]
Oof.. That isn't a helpful error message. This is caused due to the [$rmd-chip-themed-background-color](https://github.com/mlaursen/react-md/blob/7a0bb1d15393c85d07378f42e2e46fcb679e5b94/packages/chip/src/_variables.scss#L69) variable so you can override that default value for now until v2 is released.

It looks like in other places that use this function I default to either `darken`/`lighten` of the variable. I can fix this by adding the `darken`/`lighten` behavior to this variable as well or fix the error message to correctly display which variable name to change/fix:

```
Failed to compile.

./src/index.scss (./node_modules/css-loader/dist/cjs.js??ref--6-oneOf-5-1!./node_modules/postcss-loader/src??postcss!./node_modules/resolve-url-loader??ref--6-oneOf-5-3!./node_modules/sass-loader/dist/cjs.js??ref--6-oneOf-5-4!./src/index.scss)
SassError: Invalid material design color: '#3498db'. If this was intentional because your app does not use material design colors, set the '$rmd-chip-themed-background-color' variable instead to get a correct color for the provided swatch: 300.
        on line 66 of node_modules/@react-md/theme/dist/_functions.scss, in function `rmd-theme-get-swatch`
        from line 69 of node_modules/@react-md/chip/dist/_variables.scss
        from line 6 of node_modules/@react-md/chip/dist/_functions.scss
        from line 12 of node_modules/@react-md/chip/dist/_mixins.scss
        from line 7 of node_modules/react-md/dist/_react-md.scss
        from line 6 of /Users/mlaursen/code/v2-test/src/index.scss
>>       @error $error-msg;

   ------^
```

Do you think it's better to automatically fix this behind the scenes or throw an error for these types of colors? I'd like to be consistent for these if possible. A quick example of an existing automatic fix is the [$rmd-switch-ball-disabled-color](https://github.com/mlaursen/react-md/blob/7a0bb1d15393c85d07378f42e2e46fcb679e5b94/packages/form/src/toggle/_variables.scss#L84).

**Comment by lindomar-oliveira** [comment]
Keeping the simplicity of customizing the color tones, I think it would be better to fix it automatically behind the scenes.

**Comment by mlaursen** [comment]
Sounds good, I'll go with the automatic fix approach. I'll release another beta version today with this fix (and a few others).

**Comment by mlaursen** [comment]
v2.0.0-beta.2 should now be published. Let me know if the fix didn't work and I'll reopen this issue

**Comment by lindomar-oliveira** [comment]
@mlaursen *Thanks!* Worked perfectly.
