### ISSUE TITLE
Component mount twice under route in NavigationDrawer of example with-react-router v4

### ISSUE THREAD

**Issue by davidorion55555** [mlaursen/react-md#879]
**Describe the bug** A clear and concise description of what the bug is.

**To Reproduce** Steps to reproduce the behavior:

**Expected behavior** A clear and concise description of what you expected to
happen.

**Screenshots** If applicable, add screenshots to help explain your problem.

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context** Add any other context about the problem here.

**Comment by davidorion55555** [comment]
I built with-react-router v4 that is on github, component construct and mount twice under route of NavigationDrawer.
So fetch data twice from DB.

**Comment by mlaursen** [comment]
Unfortunately there isn't really a good way to handle this in v1, but it _is_ expected behavior due how the transitions are fired by changing the `key` prop on the `Switch` component in the `with-react-router-v4` example. Please check out this [codesandbox](https://codesandbox.io/s/proud-glitter-7myj6?file=/src/App.js) which fixes the issue by disabling the transition with the pathname `key`.
