### ISSUE TITLE
noto font

### ISSUE THREAD

**Issue by joeblew99** [mlaursen/react-md#99]
there is a newish font as part of md called noto.
its designed and recommended for where you need to support many languages.

i am not an expert on this. i am using this repo for a project that needs to work in lots of languages.

seeking advice...

**Comment by mlaursen** [comment]
I looked into the Noto fonts, and it might be a little bit harder since it is still in early access. So the ways you can use this font depend on how the fonts will be hosted and what languages you will be supporting. The two cases I see are: locally hosted and google fonts hosted. For each case, you will probably need to determine the user's language and then update the fonts to use that font name.

#### Locally Hosted
The idea would be to download all the Noto fonts with their languages you would be supporting. There is a nice [font mixin](../master/src/scss/helpers/mixins/_fonts.scss#L20) that you can use to create the font-faces. Then the basic idea would be to check your user's language using your server or javascript and load the correct font. Once you have all of that set up, you could add a class to the html for the correct language.

So for example loading Sundanese:

```scss
html.noto-sundanese {
   font-family: 'Noto Sans Sundanese', sans-serif;
}
```



#### Google Fonts Hosted
This would follow the same idea of detecting the user's language and setting the correct language. https://www.google.com/fonts/earlyaccess has a list of all the imports available. You could also try to use the [webfontloader](https://github.com/typekit/webfontloader#google) which would automatically load the fonts and update the html class name with the font library loaded.

But to recap:
1. Determine user's locale from server or javascript
2. Load correct Noto font library for that locale
3. Update html with a class name that will change the font family to the correct Noto font family

**Comment by joeblew99** [comment]
Thanks , that's really thorough.

I can try this out myself from the sounds of it. I will be amazed if, for example, the date time picker  works in diff locales.
